// Generated by `geam embedding sync`. Do not edit.

use geam::embedding::AsyncHostedModuleBindings;
use geam::embedding::AsyncHostedModuleBuilder;
use geam::embedding::BigInt;
use geam::embedding::BindingError;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::InputShape;
use geam::embedding::ModuleBindings;
use geam::embedding::ModuleBuilder;
use geam::embedding::Project;

pub const ROOT_MODULE: &str = "geam_rust_embedding_async_host";

pub fn project() -> Project {
    Project::new(concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"), ROOT_MODULE)
}

#[allow(dead_code, clippy::type_complexity)]
pub struct Functions {
    pub calculate: Function<(BigInt,), BigInt, Function0Input>,
}

/// Generated function handles for resumable embedding.
#[allow(dead_code, clippy::type_complexity)]
pub struct AsyncFunctions {
    pub calculate: Function<(BigInt,), BigInt, Function0Input>,
}

pub struct Function0Input;

impl InputShape<(BigInt,)> for Function0Input {}

#[allow(dead_code)]
pub fn bind(builder: ModuleBuilder) -> Result<(ModuleBindings, Functions), BindingError> {
    let (bindings, function_0) = builder.function(FunctionDeclaration::new("calculate"))?;
    Ok((
        bindings,
        Functions {
            calculate: function_0.with_input_shape(),
        },
    ))
}

/// Binds the generated handles into a resumable hosted module.
#[allow(dead_code)]
pub fn bind_async<Profile: geam::HostProfile>(
    builder: AsyncHostedModuleBuilder<Profile>,
) -> Result<(AsyncHostedModuleBindings<Profile>, AsyncFunctions), BindingError> {
    let (bindings, function_0) = builder.function(FunctionDeclaration::new("calculate"))?;
    Ok((
        bindings,
        AsyncFunctions {
            calculate: function_0.with_input_shape(),
        },
    ))
}
