// Generated by `geam embedding sync`. Do not edit.

use geam::AsyncHostComponentProfile;
use geam::AsyncHostProviderComponent;
use geam::HostProfile;
use geam::HostProviderComponent;
use geam::HostProviderComponentInitialization;
use geam::HostProviderConfiguration;
use geam::HostProviderInitializationError;
use geam::HostRegistrationError;
use geam::HostWorkProfile;
use geam::TransferHostProviderComponentRegistration as ComponentRegistration;
use geam::TransferHostProviderSet;

use geam::embedding::BigInt;
use geam::embedding::BindingError;
use geam::embedding::EcoString;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::FutureType;
use geam::embedding::InputShape;
use geam::embedding::TransferHostedProject;
use geam::embedding::WorkModuleBindings;
use geam::embedding::WorkModuleBuilder;

pub const ROOT_MODULE: &str = "geam_rust_embedding_async_host";

pub struct Profile;

pub type ProviderSet = TransferHostProviderSet<Profile>;

#[derive(Default)]
pub struct Stores {
    future: <geam::FutureComponent as AsyncHostProviderComponent>::AsyncStores,
    provider_example_async_files:
        <geam_example_async_files::Component as AsyncHostProviderComponent>::AsyncStores,
}

pub struct RunStateInputs {
    pub example_async_files: HostProviderConfiguration,
}

impl RunStateInputs {
    pub fn initialize(self) -> Result<RunState, HostProviderInitializationError> {
        Ok(RunState {
            future: (),
            provider_example_async_files:
                <geam_example_async_files::Component as HostProviderComponentInitialization>::initialize(
                    &self.example_async_files,
                )?,
        })
    }
}

pub struct RunState {
    future: <geam::FutureComponent as HostProviderComponent>::RunState,
    provider_example_async_files:
        <geam_example_async_files::Component as HostProviderComponent>::RunState,
}

impl HostProfile for Profile {
    type ExternalStores = Stores;
    type RunState = RunState;
}

impl HostWorkProfile for Profile {
    type Work = geam::FutureComponent;
}

impl AsyncHostComponentProfile<geam::FutureComponent> for Profile {
    fn component_async_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::FutureComponent as AsyncHostProviderComponent>::AsyncStores {
        &stores.future
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::FutureComponent as HostProviderComponent>::RunState {
        &mut state.future
    }
}

impl AsyncHostComponentProfile<geam_example_async_files::Component> for Profile {
    fn component_async_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam_example_async_files::Component as AsyncHostProviderComponent>::AsyncStores {
        &stores.provider_example_async_files
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam_example_async_files::Component as HostProviderComponent>::RunState {
        &mut state.provider_example_async_files
    }
}

pub fn host_providers() -> Result<ProviderSet, HostRegistrationError> {
    let mut providers = <geam::FutureComponent as ComponentRegistration<Profile>>::providers()?;
    let additional_providers =
        <geam_example_async_files::Component as ComponentRegistration<Profile>>::providers()?;
    providers.extend(additional_providers);
    TransferHostProviderSet::new(providers)
}

pub fn project() -> TransferHostedProject<Profile> {
    TransferHostedProject::new(
        concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"),
        ROOT_MODULE,
        host_providers,
    )
}

#[allow(clippy::type_complexity)]
pub struct Functions {
    pub double: Function<(BigInt,), BigInt, Function0Input>,
    pub greeting: Function<(EcoString,), FutureType<Result<EcoString, EcoString>>, Function1Input>,
}

pub struct Function0Input;

impl InputShape<(BigInt,)> for Function0Input {}

pub struct Function1Input;

impl InputShape<(EcoString,)> for Function1Input {}

pub fn bind(
    builder: WorkModuleBuilder<Profile>,
) -> Result<(WorkModuleBindings<Profile>, Functions), BindingError> {
    let (mut bindings, function_0) = builder.function(FunctionDeclaration::new("double"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("greeting"))?;
    Ok((
        bindings,
        Functions {
            double: function_0.with_input_shape(),
            greeting: function_1.with_input_shape(),
        },
    ))
}
