// Generated by `geam embedding sync`. Do not edit.

use geam::embedding::BigInt;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::InputShape;
use geam::embedding::Module;
use geam::embedding::PreparedError;

mod program;

#[allow(dead_code, clippy::type_complexity)]
pub struct Functions {
    pub double: Function<(BigInt,), BigInt, Function0Input>,
}

pub struct Function0Input;

impl InputShape<(BigInt,)> for Function0Input {}

pub fn load() -> Result<(Module, Functions), PreparedError> {
    let mut bindings = program::PROGRAM.load()?;
    let function_0 = bindings.function(FunctionDeclaration::new("double"))?;
    Ok((
        bindings.seal(),
        Functions {
            double: function_0.with_input_shape(),
        },
    ))
}
