// Generated by `geam embedding sync`. Do not edit.

use geam::HostProfile;
use geam::HostProviderSet;
use geam::HostRegistrationError;

use geam::embedding::BigInt;
use geam::embedding::BindingError;
use geam::embedding::CallableType;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::HostedModuleBindings;
use geam::embedding::HostedModuleBuilder;
use geam::embedding::HostedProject;
use geam::embedding::InputShape;
use geam::embedding::PreparedError;
use geam::embedding::PreparedHostedModuleBindings;

pub const ROOT_MODULE: &str = "geam_rust_embedding_callables";

mod program;

/// Opaque `geam_rust_embedding_callables:geam_rust_embedding_callables.Saved` in this execution domain.
pub type Type0 = geam::embedding::CustomType<Type0Schema>;

pub struct Type0Schema;

impl geam::embedding::NamedTypeSchema for Type0Schema {
    const PACKAGE: &'static str = "geam_rust_embedding_callables";
    const MODULE: &'static str = "geam_rust_embedding_callables";
    const NAME: &'static str = "Saved";
}

pub struct Profile;

pub type ProviderSet = HostProviderSet<Profile>;

#[derive(Default)]
pub struct Stores {}

pub struct RunStateInputs {}

impl RunStateInputs {
    pub fn initialize(self) -> RunState {
        RunState {}
    }
}

pub struct RunState {}

impl HostProfile for Profile {
    type ExternalStores = Stores;
    type RunState = RunState;
    type ExecutionState = ();
}

pub fn host_providers() -> Result<ProviderSet, HostRegistrationError> {
    HostProviderSet::from_providers([])
}

#[allow(dead_code)]
pub fn project<Application: HostProfile>(
    providers: fn() -> Result<HostProviderSet<Application>, HostRegistrationError>,
) -> HostedProject<Application> {
    HostedProject::new(
        concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"),
        ROOT_MODULE,
        providers,
    )
}

#[allow(clippy::type_complexity)]
pub struct Functions {
    pub calculate: Function<(BigInt, CallableType<(BigInt,), BigInt>), BigInt, Function0Input>,
    pub keep: Function<
        (CallableType<(BigInt,), BigInt>,),
        CallableType<(BigInt,), BigInt>,
        Function1Input,
    >,
    pub save: Function<(CallableType<(BigInt,), BigInt>,), Type0, Function2Input>,
    pub restore: Function<(Type0,), CallableType<(BigInt,), BigInt>, Function3Input>,
    pub wrapped: Function<
        (CallableType<(BigInt,), BigInt>,),
        CallableType<(BigInt,), BigInt>,
        Function4Input,
    >,
}

pub struct Function0Input;

impl<Input0> InputShape<(BigInt, Input0)> for Function0Input {}

pub struct Function1Input;

impl<Input0> InputShape<(Input0,)> for Function1Input {}

pub struct Function2Input;

impl<Input0> InputShape<(Input0,)> for Function2Input {}

pub struct Function3Input;

impl<Input0> InputShape<(Input0,)> for Function3Input {}

pub struct Function4Input;

impl<Input0> InputShape<(Input0,)> for Function4Input {}

#[allow(dead_code)]
pub fn bind<Application: HostProfile>(
    builder: HostedModuleBuilder<Application>,
) -> Result<(HostedModuleBindings<Application>, Functions), BindingError> {
    let (mut bindings, function_0) = builder.function(FunctionDeclaration::new("calculate"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("keep"))?;
    let function_2 = bindings.function(FunctionDeclaration::new("save"))?;
    let function_3 = bindings.function(FunctionDeclaration::new("restore"))?;
    let function_4 = bindings.function(FunctionDeclaration::new("wrapped"))?;
    Ok((
        bindings,
        Functions {
            calculate: function_0.with_input_shape(),
            keep: function_1.with_input_shape(),
            save: function_2.with_input_shape(),
            restore: function_3.with_input_shape(),
            wrapped: function_4.with_input_shape(),
        },
    ))
}

#[allow(dead_code)]
pub fn load<Application: HostProfile>(
    providers: HostProviderSet<Application>,
) -> Result<(PreparedHostedModuleBindings<Application>, Functions), PreparedError> {
    let mut bindings = program::PROGRAM.load(providers)?;
    let function_0 = bindings.function(FunctionDeclaration::new("calculate"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("keep"))?;
    let function_2 = bindings.function(FunctionDeclaration::new("save"))?;
    let function_3 = bindings.function(FunctionDeclaration::new("restore"))?;
    let function_4 = bindings.function(FunctionDeclaration::new("wrapped"))?;
    Ok((
        bindings,
        Functions {
            calculate: function_0.with_input_shape(),
            keep: function_1.with_input_shape(),
            save: function_2.with_input_shape(),
            restore: function_3.with_input_shape(),
            wrapped: function_4.with_input_shape(),
        },
    ))
}

// Application declarations: sha256:505b6e6ce9571d1cd43d0f396982d85083c8f5d95c74313eb903932f00a4c9d8
