name = "text_pattern_example"
version = "0.1.0"
description = "Text pattern example for Erlang and Geam"
licences = ["Apache-2.0"]

[dependencies]
example_text_pattern = { path = "packages/example_text_pattern" }
