// Generated by `geam embedding sync`. Do not edit.

use geam::HostComponentProfile;
use geam::HostModule;
use geam::HostProfile;
use geam::HostProviderComponent;
use geam::HostProviderComponentInitialization;
use geam::HostProviderComponentRegistration;
use geam::HostProviderConfiguration;
use geam::HostProviderInitializationError;
use geam::HostProviderSet;
use geam::HostRegistrationError;

use geam::embedding::BigInt;
use geam::embedding::BindingError;
use geam::embedding::EcoString;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::HostedModuleBindings;
use geam::embedding::HostedModuleBuilder;
use geam::embedding::HostedProject;
use geam::embedding::InputShape;
use geam::embedding::List;
use std::marker::PhantomData;

pub const ROOT_MODULE: &str = "rust_embedding";

pub struct Profile<Io>(PhantomData<fn() -> Io>);

pub type ProviderSet<Io> = HostProviderSet<Profile<Io>>;

pub struct Stores<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores,
    provider_example_text_pattern: <patterns::Component as HostProviderComponent>::Stores,
}

impl<Io> Default for Stores<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn default() -> Self {
        Self {
            stdlib: Default::default(),
            provider_example_text_pattern: Default::default(),
        }
    }
}

pub struct RunStateInputs<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub stdlib: geam::gleam_stdlib::GleamStdlibRunState<Io>,
    pub example_text_pattern: HostProviderConfiguration,
}

impl<Io> RunStateInputs<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub fn initialize(self) -> Result<RunState<Io>, HostProviderInitializationError> {
        Ok(RunState {
            stdlib: self.stdlib,
            provider_example_text_pattern:
                <patterns::Component as HostProviderComponentInitialization>::initialize(
                    &self.example_text_pattern,
                )?,
        })
    }
}

pub struct RunState<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState,
    provider_example_text_pattern: <patterns::Component as HostProviderComponent>::RunState,
}

impl<Io> RunState<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub fn stdlib(&self) -> &geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &self.stdlib
    }

    pub fn stdlib_mut(&mut self) -> &mut geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &mut self.stdlib
    }
}

impl<Io> HostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type ExternalStores = Stores<Io>;
    type RunState = RunState<Io>;
}

impl<Io> HostComponentProfile<geam::gleam_stdlib::Component<Io>> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores {
        &stores.stdlib
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState {
        &mut state.stdlib
    }
}

impl<Io> HostComponentProfile<patterns::Component> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<patterns::Component as HostProviderComponent>::Stores {
        &stores.provider_example_text_pattern
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <patterns::Component as HostProviderComponent>::RunState {
        &mut state.provider_example_text_pattern
    }
}

impl<Io> geam::gleam_stdlib::GleamStdlibHostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type Io = Io;
}

pub fn host_providers<Io>() -> Result<ProviderSet<Io>, HostRegistrationError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let mut providers = <geam::gleam_stdlib::Component<Io> as HostProviderComponentRegistration<
        Profile<Io>,
    >>::providers()?;
    let additional_providers =
        <patterns::Component as HostProviderComponentRegistration<Profile<Io>>>::providers()?;
    providers.extend(additional_providers);
    HostProviderSet::with_providers(Vec::<HostModule<Profile<Io>>>::new(), providers)
}

pub fn project<Io>() -> Result<HostedProject<Profile<Io>>, HostRegistrationError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    Ok(HostedProject::new(
        concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"),
        ROOT_MODULE,
        host_providers()?,
    ))
}

#[allow(clippy::type_complexity)]
pub struct Functions {
    pub validate_batch: Function<
        (List<(EcoString, BigInt)>,),
        List<Result<(EcoString, BigInt), EcoString>>,
        Function0Input,
    >,
    pub total_quantity:
        Function<(List<Result<(EcoString, BigInt), EcoString>>,), BigInt, Function1Input>,
    pub first_valid: Function<
        (List<Result<(EcoString, BigInt), EcoString>>,),
        Option<(EcoString, BigInt)>,
        Function2Input,
    >,
}

pub struct Function0Input;

impl<Input0> InputShape<(Input0,)> for Function0Input {}

pub struct Function1Input;

impl<Input0> InputShape<(Input0,)> for Function1Input {}

pub struct Function2Input;

impl<Input0> InputShape<(Input0,)> for Function2Input {}

pub fn bind<Io>(
    builder: HostedModuleBuilder<Profile<Io>>,
) -> Result<(HostedModuleBindings<Profile<Io>>, Functions), BindingError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let (mut bindings, function_0) =
        builder.function(FunctionDeclaration::new("validate_batch"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("total_quantity"))?;
    let function_2 = bindings.function(FunctionDeclaration::new("first_valid"))?;
    Ok((
        bindings,
        Functions {
            validate_batch: function_0.with_input_shape(),
            total_quantity: function_1.with_input_shape(),
            first_valid: function_2.with_input_shape(),
        },
    ))
}
