// Generated by `geam embedding sync`. Do not edit.

use geam::HostComponentProfile;
use geam::HostModule;
use geam::HostProfile;
use geam::HostProviderComponent;
use geam::HostProviderComponentInitialization;
use geam::HostProviderComponentRegistration;
use geam::HostProviderConfiguration;
use geam::HostProviderInitializationError;
use geam::HostProviderSet;
use geam::HostRegistrationError;

use geam::embedding::BindingError;
use geam::embedding::EcoString;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::HostedModuleBindings;
use geam::embedding::HostedModuleBuilder;
use geam::embedding::HostedProject;
use std::marker::PhantomData;

pub const ROOT_MODULE: &str = "rust_embedding";

pub struct Profile<Io>(PhantomData<fn() -> Io>);

pub type ProviderSet<Io> = HostProviderSet<Profile<Io>>;

pub struct Stores<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores,
    provider_example_text_pattern: <patterns::Component as HostProviderComponent>::Stores,
}

impl<Io> Default for Stores<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn default() -> Self {
        Self {
            stdlib: Default::default(),
            provider_example_text_pattern: Default::default(),
        }
    }
}

pub struct ProviderConfigurations {
    pub example_text_pattern: HostProviderConfiguration,
}

pub struct RunState<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState,
    provider_example_text_pattern: <patterns::Component as HostProviderComponent>::RunState,
}

impl<Io> RunState<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub fn initialize(
        stdlib: geam::gleam_stdlib::GleamStdlibRunState<Io>,
        configurations: ProviderConfigurations,
    ) -> Result<Self, HostProviderInitializationError> {
        Ok(Self {
            stdlib,
            provider_example_text_pattern:
                <patterns::Component as HostProviderComponentInitialization>::initialize(
                    &configurations.example_text_pattern,
                )?,
        })
    }

    pub fn stdlib(&self) -> &geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &self.stdlib
    }

    pub fn stdlib_mut(&mut self) -> &mut geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &mut self.stdlib
    }
}

impl<Io> HostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type ExternalStores = Stores<Io>;
    type RunState = RunState<Io>;
}

impl<Io> HostComponentProfile<geam::gleam_stdlib::Component<Io>> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores {
        &stores.stdlib
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState {
        &mut state.stdlib
    }
}

impl<Io> HostComponentProfile<patterns::Component> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<patterns::Component as HostProviderComponent>::Stores {
        &stores.provider_example_text_pattern
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <patterns::Component as HostProviderComponent>::RunState {
        &mut state.provider_example_text_pattern
    }
}

impl<Io> geam::gleam_stdlib::GleamStdlibHostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type Io = Io;
}

pub fn host_providers<Io>() -> Result<ProviderSet<Io>, HostRegistrationError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let mut providers = <geam::gleam_stdlib::Component<Io> as HostProviderComponentRegistration<
        Profile<Io>,
    >>::providers()?;
    providers.extend(
        <patterns::Component as HostProviderComponentRegistration<Profile<Io>>>::providers()?,
    );
    HostProviderSet::with_providers(Vec::<HostModule<Profile<Io>>>::new(), providers)
}

pub fn project<Io>() -> Result<HostedProject<Profile<Io>>, HostRegistrationError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    Ok(HostedProject::new(
        concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"),
        ROOT_MODULE,
        host_providers()?,
    ))
}

pub struct Functions {
    pub format_words: Function<(EcoString,), EcoString>,
    pub contains_only_words: Function<(EcoString,), bool>,
    pub choose_price: Function<(bool, f64, f64), f64>,
}

pub fn bind<Io>(
    builder: HostedModuleBuilder<Profile<Io>>,
) -> Result<(HostedModuleBindings<Profile<Io>>, Functions), BindingError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let (mut bindings, function_0) = builder.function(FunctionDeclaration::new("format_words"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("contains_only_words"))?;
    let function_2 = bindings.function(FunctionDeclaration::new("choose_price"))?;
    Ok((
        bindings,
        Functions {
            format_words: function_0,
            contains_only_words: function_1,
            choose_price: function_2,
        },
    ))
}
