use super::{binary_path, checked, command, copy_source, standalone_build};
use std::fs;
use std::path::Path;

#[test]
fn raw_strings_run_dynamic_prepared_and_relocated_standalone_debug_and_release() {
    let temporary = tempfile::tempdir().unwrap();
    let root = fs::canonicalize(temporary.path()).unwrap();
    let repository = Path::new(env!("CARGO_MANIFEST_DIR"));
    let source = repository.join("tests/fixtures/raw_string_values");
    let fixture = root.join("fixture");
    for part in ["project", "provider", "embedding"] {
        copy_source(&source.join(part), &fixture.join(part));
    }
    let provider_manifest = fixture.join("provider/Cargo.toml");
    let mut provider: toml::Value =
        toml::from_str(&fs::read_to_string(&provider_manifest).unwrap()).unwrap();
    for section in ["dependencies", "dev-dependencies"] {
        provider[section]["geam"]["path"] = repository.to_str().unwrap().into();
    }
    fs::write(provider_manifest, toml::to_string(&provider).unwrap()).unwrap();
    let application = fixture.join("embedding");
    let manifest = application.join("Cargo.toml");
    let mut package: toml::Value = toml::from_str(&fs::read_to_string(&manifest).unwrap()).unwrap();
    package["patch"]["crates-io"]["geam"]["path"] = repository.to_str().unwrap().into();
    fs::write(manifest, toml::to_string(&package).unwrap()).unwrap();
    let target = repository.join("target/prepared-acceptance");
    let target_path = target.to_str().unwrap();
    let repository_path = repository.to_str().unwrap();
    fs::create_dir_all(application.join(".cargo")).unwrap();
    fs::write(
        application.join(".cargo/config.toml"),
        toml::to_string(&toml::toml! {
            [net]
            offline = true
            [build]
            target-dir = target_path
        })
        .unwrap(),
    )
    .unwrap();
    let program = application.join("src/geam_bindings/program.rs");
    if program.exists() {
        fs::remove_file(&program).unwrap();
    }
    checked(command(env!("CARGO_BIN_EXE_geam"), &application).args(["embedding", "sync"]));
    let generated = fs::read(&program).unwrap();
    // The caller executes count_prefix on a raw tail; its admitted implementation
    // uses the generated byte view instead of a text conversion.
    let emitted = std::str::from_utf8(&generated).unwrap();
    assert!(emitted.contains("data::compiled::CompiledImplementation::String("));
    assert!(emitted.contains("values.bytes(b0_s0).starts_with(\"λ\".as_bytes())"));
    checked(command(env!("CARGO_BIN_EXE_geam"), &application).args(["embedding", "check"]));
    checked(command(env!("CARGO_BIN_EXE_geam"), &application).args(["embedding", "sync"]));
    assert_eq!(fs::read(&program).unwrap(), generated);
    checked(command("cargo", &application).args(["fmt", "--all", "--check"]));
    checked(command("cargo", &application).args([
        "clippy",
        "--all-targets",
        "--locked",
        "--",
        "-D",
        "warnings",
    ]));
    let expected = b"s3pPLMBiTxaQ9kYGzzhZRbK+xOo=\n\xff\xfe\n";
    let output = checked(command("cargo", &application).args(["run", "--quiet", "--locked"]));
    assert_eq!(output.stdout, expected.repeat(4));
    assert!(output.stderr.is_empty());
    let deployment = root.join("deployment");
    fs::create_dir(&deployment).unwrap();
    let embedding = binary_path(&deployment, "raw-string-embedding");
    fs::copy(
        binary_path(&target.join("debug"), "raw-string-values-embedding"),
        &embedding,
    )
    .unwrap();

    let project = fixture.join("project");
    fs::create_dir_all(project.join(".cargo")).unwrap();
    fs::write(
        project.join(".cargo/config.toml"),
        toml::to_string(&toml::toml! {
            [patch.crates-io.geam]
            path = repository_path
            [net]
            offline = true
        })
        .unwrap(),
    )
    .unwrap();
    checked(command(env!("CARGO_BIN_EXE_geam"), &project).args([
        "provider",
        "add",
        "--path",
        "../provider",
    ]));
    let mut standalone = Vec::new();
    for release in [false, true] {
        let mut build = standalone_build(&project);
        if release {
            build.arg("--release");
        }
        let output = checked(&mut build);
        assert!(output.stdout.is_empty());
        let report = std::str::from_utf8(&output.stderr).unwrap();
        let built = report
            .lines()
            .last()
            .unwrap()
            .strip_prefix("geam: Built ")
            .unwrap();
        let executable = binary_path(
            &deployment,
            if release { "raw-release" } else { "raw-debug" },
        );
        fs::copy(built, &executable).unwrap();
        standalone.push(executable);
    }
    fs::remove_dir_all(fixture).unwrap();
    for _ in 0..2 {
        let output = checked(
            command(&embedding, &deployment)
                .arg("--prepared")
                .env("PATH", ""),
        );
        assert_eq!(output.stdout, expected.repeat(2));
        assert!(output.stderr.is_empty());
        for executable in &standalone {
            let output = checked(command(executable, &deployment).env("PATH", ""));
            assert_eq!(output.stdout, expected);
            assert!(output.stderr.is_empty());
        }
    }
}
