// Generated by `geam embedding sync`. Do not edit.

use geam::HostComponentProfile;
use geam::HostProfile;
use geam::HostProviderComponent;
use geam::HostProviderComponentRegistration as ComponentRegistration;
use geam::HostProviderSet;
use geam::HostRegistrationError;
use geam::HostWorkProfile;

use geam::embedding::BigInt;
use geam::embedding::BindingError;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::HostedModuleBindings;
use geam::embedding::HostedModuleBuilder;
use geam::embedding::HostedProject;
use geam::embedding::InputShape;
use std::marker::PhantomData;

pub const ROOT_MODULE: &str = "geam_rust_embedding_processes";

/// Opaque `gleam_erlang:gleam/erlang/process.Pid` in this execution domain.
pub type Type0 = geam::embedding::ExternalType<Type0Schema>;

pub struct Type0Schema;

impl geam::embedding::NamedTypeSchema for Type0Schema {
    const PACKAGE: &'static str = "gleam_erlang";
    const MODULE: &'static str = "gleam/erlang/process";
    const NAME: &'static str = "Pid";
}

/// Opaque `gleam_erlang:gleam/erlang/process.Subject` in this execution domain.
pub type Type1 = geam::embedding::CustomType<Type1Schema>;

pub struct Type1Schema;

impl geam::embedding::NamedTypeSchema for Type1Schema {
    const PACKAGE: &'static str = "gleam_erlang";
    const MODULE: &'static str = "gleam/erlang/process";
    const NAME: &'static str = "Subject";

    fn arguments() -> Vec<geam::ValueType> {
        use geam::ValueType;

        let type_0 = geam::plan::CustomTypeName::new(
            "geam_rust_embedding_processes".into(),
            "geam_rust_embedding_processes".into(),
            "Request".into(),
        );
        let type_1 = vec![];
        let type_2 = geam::plan::CustomType::new(type_0, type_1);
        let type_3 = ValueType::Custom(type_2);
        vec![type_3]
    }
}

pub struct Profile<Io>(PhantomData<fn() -> Io>);

pub type ProviderSet<Io> = HostProviderSet<Profile<Io>>;

pub struct Stores<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    future: <geam::FutureComponent as HostProviderComponent>::Stores,
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores,
    erlang: <geam::gleam_erlang::Component<Profile<Io>> as HostProviderComponent>::Stores,
}

impl<Io> Default for Stores<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn default() -> Self {
        Self {
            future: Default::default(),
            stdlib: Default::default(),
            erlang: Default::default(),
        }
    }
}

pub struct RunStateInputs<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub stdlib: geam::gleam_stdlib::GleamStdlibRunState<Io>,
    pub erlang: geam::gleam_erlang::Configuration,
}

impl<Io> RunStateInputs<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub fn initialize(self) -> RunState<Io> {
        RunState {
            future: (),
            stdlib: self.stdlib,
            erlang: self.erlang,
        }
    }
}

pub struct RunState<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    future: <geam::FutureComponent as HostProviderComponent>::RunState,
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState,
    erlang: <geam::gleam_erlang::Component<Profile<Io>> as HostProviderComponent>::RunState,
}

impl<Io> RunState<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub fn stdlib(&self) -> &geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &self.stdlib
    }

    pub fn stdlib_mut(&mut self) -> &mut geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &mut self.stdlib
    }
}

impl<Io> HostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type ExternalStores = Stores<Io>;
    type RunState = RunState<Io>;
    type ExecutionState = geam::gleam_erlang::ErlangExecution;
}

impl<Io> HostWorkProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type Work = geam::FutureComponent;
}

impl<Io> HostComponentProfile<geam::FutureComponent> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::FutureComponent as HostProviderComponent>::Stores {
        &stores.future
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::FutureComponent as HostProviderComponent>::RunState {
        &mut state.future
    }
}

impl<Io> HostComponentProfile<geam::gleam_stdlib::Component<Io>> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores {
        &stores.stdlib
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState {
        &mut state.stdlib
    }
}

impl<Io> HostComponentProfile<geam::gleam_erlang::Component<Profile<Io>>> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::gleam_erlang::Component<Profile<Io>> as HostProviderComponent>::Stores {
        &stores.erlang
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::gleam_erlang::Component<Profile<Io>> as HostProviderComponent>::RunState {
        &mut state.erlang
    }
}

impl<Io> geam::gleam_stdlib::GleamStdlibHostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type Io = Io;
}

impl<Io> geam::gleam_erlang::GleamErlangHostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn erlang_execution(
        state: &mut Self::ExecutionState,
    ) -> &mut geam::gleam_erlang::ErlangExecution {
        state
    }
}

pub fn host_providers<Io>() -> Result<ProviderSet<Io>, HostRegistrationError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let mut providers =
        <geam::gleam_stdlib::Component<Io> as ComponentRegistration<Profile<Io>>>::providers()?;
    let additional_providers =
        <geam::gleam_erlang::Component<Profile<Io>> as ComponentRegistration<
            Profile<Io>,
        >>::providers()?;
    providers.extend(additional_providers);
    HostProviderSet::from_providers(providers)
}

pub fn project<Io>() -> HostedProject<Profile<Io>>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    HostedProject::new(
        concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"),
        ROOT_MODULE,
        host_providers::<Io>,
    )
}

#[allow(clippy::type_complexity)]
pub struct Functions {
    pub start: Function<(), (Type0, Type1), Function0Input>,
    pub add: Function<(Type1, BigInt), BigInt, Function1Input>,
    pub is_alive: Function<(Type0,), bool, Function2Input>,
    pub stop: Function<(Type0, Type1), bool, Function3Input>,
    pub main: Function<(), bool, Function4Input>,
}

pub struct Function0Input;

impl InputShape<()> for Function0Input {}

pub struct Function1Input;

impl<Input0> InputShape<(Input0, BigInt)> for Function1Input {}

pub struct Function2Input;

impl<Input0> InputShape<(Input0,)> for Function2Input {}

pub struct Function3Input;

impl<Input0, Input1> InputShape<(Input0, Input1)> for Function3Input {}

pub struct Function4Input;

impl InputShape<()> for Function4Input {}

pub fn bind<Io>(
    builder: HostedModuleBuilder<Profile<Io>>,
) -> Result<(HostedModuleBindings<Profile<Io>>, Functions), BindingError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let (mut bindings, function_0) = builder.function(FunctionDeclaration::new("start"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("add"))?;
    let function_2 = bindings.function(FunctionDeclaration::new("is_alive"))?;
    let function_3 = bindings.function(FunctionDeclaration::new("stop"))?;
    let function_4 = bindings.function(FunctionDeclaration::new("main"))?;
    Ok((
        bindings,
        Functions {
            start: function_0.with_input_shape(),
            add: function_1.with_input_shape(),
            is_alive: function_2.with_input_shape(),
            stop: function_3.with_input_shape(),
            main: function_4.with_input_shape(),
        },
    ))
}
