[package]
name = "geam-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Typed Gleam planning, host, and execution core for Geam"
license.workspace = true
repository.workspace = true
publish = ["crates-io"]

[dependencies]
bitvec.workspace = true
camino.workspace = true
ecow.workspace = true
gleam-compiler-core.workspace = true
half.workspace = true
im.workspace = true
miette.workspace = true
num-bigint.workspace = true
thiserror.workspace = true
toml.workspace = true
vec1.workspace = true

[dev-dependencies]
miette = { workspace = true, features = ["fancy-no-backtrace"] }
tempfile.workspace = true
