// Generated by `geam embedding sync`. Do not edit.

use geam::HostProfile;
use geam::HostProviderSet;
use geam::HostRegistrationError;

use geam::embedding::BigInt;
use geam::embedding::BindingError;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::HostedModuleBindings;
use geam::embedding::HostedModuleBuilder;
use geam::embedding::HostedProject;
use geam::embedding::InputShape;

pub const ROOT_MODULE: &str = "geam_rust_embedding_session";

/// Opaque `geam_rust_embedding_session:geam_rust_embedding_session.Session` in this execution domain.
pub type Type0 = geam::embedding::CustomType<Type0Schema>;

pub struct Type0Schema;

impl geam::embedding::NamedTypeSchema for Type0Schema {
    const PACKAGE: &'static str = "geam_rust_embedding_session";
    const MODULE: &'static str = "geam_rust_embedding_session";
    const NAME: &'static str = "Session";
}

pub struct Profile;

pub type ProviderSet = HostProviderSet<Profile>;

#[derive(Default)]
pub struct Stores {}

pub struct RunStateInputs {}

impl RunStateInputs {
    pub fn initialize(self) -> RunState {
        RunState {}
    }
}

pub struct RunState {}

impl HostProfile for Profile {
    type ExternalStores = Stores;
    type RunState = RunState;
}

pub fn host_providers() -> Result<ProviderSet, HostRegistrationError> {
    HostProviderSet::from_providers([])
}

pub fn project() -> HostedProject<Profile> {
    HostedProject::new(
        concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"),
        ROOT_MODULE,
        host_providers,
    )
}

#[allow(clippy::type_complexity)]
pub struct Functions {
    pub start: Function<(BigInt,), Type0, Function0Input>,
    pub next: Function<(Type0,), Type0, Function1Input>,
    pub total: Function<(Type0,), BigInt, Function2Input>,
}

pub struct Function0Input;

impl InputShape<(BigInt,)> for Function0Input {}

pub struct Function1Input;

impl<Input0> InputShape<(Input0,)> for Function1Input {}

pub struct Function2Input;

impl<Input0> InputShape<(Input0,)> for Function2Input {}

pub fn bind(
    builder: HostedModuleBuilder<Profile>,
) -> Result<(HostedModuleBindings<Profile>, Functions), BindingError> {
    let (mut bindings, function_0) = builder.function(FunctionDeclaration::new("start"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("next"))?;
    let function_2 = bindings.function(FunctionDeclaration::new("total"))?;
    Ok((
        bindings,
        Functions {
            start: function_0.with_input_shape(),
            next: function_1.with_input_shape(),
            total: function_2.with_input_shape(),
        },
    ))
}
