[package]
name = "geam-rust-embedding-application"
version = "0.1.0"
edition = "2024"
rust-version = "1.96"
publish = false

[dependencies]
geam = { path = "../../..", default-features = false, features = ["embedding", "gleam-stdlib"] }
patterns = { package = "geam-example-text-pattern", path = "../../provider/text_pattern/provider" }

[patch.crates-io]
geam = { path = "../../.." }

[workspace]
resolver = "3"
