[package]
name = "geam-otp-service-fixture"
version = "0.1.0"
edition = "2024"
publish = false

[package.metadata.geam.provider]
schema = 2
gleam-package = "gleam_otp"
gleam-version = ">= 1.3.0 and < 1.3.1"
component = "profile"
execution-service = false
requires-services = ["gleam_erlang"]

[dependencies]
geam = { version = "=0.2.3", default-features = false, features = ["provider", "gleam-erlang"] }

[dev-dependencies]
camino = "1"
sha2 = "0.10"

[patch.crates-io]
geam = { path = "../../../.." }

[workspace]
resolver = "3"
