use ecow::EcoString;
use num_bigint::BigInt;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Token {
    Name { name: EcoString },
    UpName { name: EcoString },
    DiscardName { name: EcoString },
    Int { value: EcoString, int_value: BigInt },
    Float { value: EcoString },
    String { value: EcoString },
    LeftParen,
    RightParen,
    LeftSquare,
    RightSquare,
    LeftBrace,
    RightBrace,
    Plus,
    Minus,
    Star,
    Slash,
    Less,
    Greater,
    LessEqual,
    GreaterEqual,
    Percent,
    PlusDot,
    MinusDot,
    StarDot,
    SlashDot,
    LessDot,
    GreaterDot,
    LessEqualDot,
    GreaterEqualDot,
    Concatenate,
    Colon,
    Comma,
    Hash,
    Bang,
    Equal,
    EqualEqual,
    NotEqual,
    Vbar,
    VbarVbar,
    AmperAmper,
    LtLt,
    GtGt,
    Pipe,
    Dot,
    RArrow,
    LArrow,
    DotDot,
    At,
    As,
    Assert,
    Case,
    Const,
    Echo,
    Fn,
    If,
    Import,
    Let,
    Opaque,
    Panic,
    Pub,
    Todo,
    Type,
    Use,
    NewLine,
    EndOfFile,
}

impl Token {
    pub fn same_variant(&self, other: &Self) -> bool {
        std::mem::discriminant(self) == std::mem::discriminant(other)
    }
}
