use crate::error::CliError;
use camino::{Utf8Path, Utf8PathBuf};
use std::fs;
use std::io::Write;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum SyncOutcome {
    Unchanged,
    Updated,
}

pub(super) fn program_path(destination: &Utf8Path) -> Utf8PathBuf {
    destination.with_extension("").join("program.rs")
}

pub(super) fn validate_generated_set(
    destination: &Utf8Path,
    prepared: bool,
) -> Result<(), CliError> {
    if prepared {
        let directory = destination.with_extension("");
        match fs::symlink_metadata(&directory) {
            Ok(metadata) if metadata.is_dir() => {}
            Ok(_) => {
                return Err(CliError::EmbeddingFileConflict {
                    path: directory,
                    reason: "prepared data requires a directory, not a file or symbolic link"
                        .to_owned(),
                });
            }
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => {
                return Err(CliError::FileRead {
                    path: directory,
                    error,
                });
            }
        }
        validate_generated(&program_path(destination))?;
    }
    validate_generated(destination)
}

pub(super) fn check_generated(
    manifest: &Utf8Path,
    destination: &Utf8Path,
    source: &[u8],
    program: Option<&[u8]>,
) -> Result<(), CliError> {
    check(manifest, destination, source)?;
    let path = program_path(destination);
    match program {
        Some(expected) => check(manifest, &path, expected),
        None if obsolete_program(destination)? => Err(out_of_date(manifest, &path)),
        None => Ok(()),
    }
}

pub(super) fn sync_generated(
    destination: &Utf8Path,
    source: &[u8],
    program: Option<&[u8]>,
) -> Result<SyncOutcome, CliError> {
    validate_generated_set(destination, program.is_some())?;
    let path = program_path(destination);
    let root = stage(destination, source)?;
    let child = match program {
        Some(expected) => {
            let directory = path.with_file_name("");
            fs::create_dir_all(&directory).map_err(|error| CliError::FileWrite {
                path: directory,
                error,
            })?;
            stage(&path, expected)?
        }
        None => None,
    };
    let obsolete = program.is_none() && obsolete_program(destination)?;
    publish_generated(destination, root, child, obsolete)
}

fn publish_generated(
    destination: &Utf8Path,
    root: Option<tempfile::NamedTempFile>,
    child: Option<tempfile::NamedTempFile>,
    obsolete: bool,
) -> Result<SyncOutcome, CliError> {
    let path = program_path(destination);
    let changed = root.is_some() || child.is_some() || obsolete;
    // Stage both files before replacing either; an interrupted set is detected by check.
    if let Some(child) = child {
        publish(child, &path)?;
    }
    if let Some(root) = root {
        publish(root, destination)?;
    }
    if obsolete {
        fs::remove_file(&path).map_err(|error| CliError::FileWrite { path, error })?;
    }
    Ok(if changed {
        SyncOutcome::Updated
    } else {
        SyncOutcome::Unchanged
    })
}

fn obsolete_program(destination: &Utf8Path) -> Result<bool, CliError> {
    let directory = destination.with_extension("");
    match fs::symlink_metadata(&directory) {
        Ok(metadata) if !metadata.is_dir() => return Ok(false),
        Ok(_) => {}
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(false),
        Err(error) => {
            return Err(CliError::FileRead {
                path: directory,
                error,
            });
        }
    }
    let path = program_path(destination);
    match fs::read(&path) {
        Ok(bytes) => Ok(has_generated_header(&bytes)),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(false),
        Err(error) => Err(CliError::FileRead { path, error }),
    }
}

pub(super) fn validate_generated(destination: &Utf8Path) -> Result<(), CliError> {
    match fs::read(destination) {
        Ok(current) if has_generated_header(&current) => Ok(()),
        Ok(_) => Err(CliError::EmbeddingFileConflict {
            path: destination.to_path_buf(),
            reason: "the file was not generated by geam embedding sync".to_owned(),
        }),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(CliError::FileRead {
            path: destination.to_path_buf(),
            error,
        }),
    }
}

fn has_generated_header(bytes: &[u8]) -> bool {
    let marker = super::GENERATED_HEADER.trim_end_matches('\n').as_bytes();
    bytes
        .strip_prefix(marker)
        .is_some_and(|remaining| remaining.starts_with(b"\n") || remaining.starts_with(b"\r\n"))
}

pub(super) fn check(
    manifest: &Utf8Path,
    destination: &Utf8Path,
    expected: &[u8],
) -> Result<(), CliError> {
    match fs::read(destination) {
        Ok(current) if current == expected => Ok(()),
        Ok(_) => Err(out_of_date(manifest, destination)),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            Err(out_of_date(manifest, destination))
        }
        Err(error) => Err(CliError::FileRead {
            path: destination.to_path_buf(),
            error,
        }),
    }
}

pub(super) fn sync(
    directory: &Utf8Path,
    destination: &Utf8Path,
    expected: &[u8],
) -> Result<SyncOutcome, CliError> {
    let Some(temporary) = stage_in(directory, destination, expected)? else {
        return Ok(SyncOutcome::Unchanged);
    };
    publish(temporary, destination)?;
    Ok(SyncOutcome::Updated)
}

fn stage(
    destination: &Utf8Path,
    expected: &[u8],
) -> Result<Option<tempfile::NamedTempFile>, CliError> {
    stage_in(&destination.with_file_name(""), destination, expected)
}

fn stage_in(
    directory: &Utf8Path,
    destination: &Utf8Path,
    expected: &[u8],
) -> Result<Option<tempfile::NamedTempFile>, CliError> {
    match fs::read(destination) {
        Ok(current) if current == expected => return Ok(None),
        Ok(_) => {}
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
        Err(error) => {
            return Err(CliError::FileRead {
                path: destination.to_path_buf(),
                error,
            });
        }
    }

    let mut temporary =
        tempfile::NamedTempFile::new_in(directory).map_err(|error| CliError::FileWrite {
            path: destination.to_path_buf(),
            error,
        })?;
    write_expected(&mut temporary, destination, expected).map(|()| Some(temporary))
}

fn publish(temporary: tempfile::NamedTempFile, destination: &Utf8Path) -> Result<(), CliError> {
    temporary
        .persist(destination)
        .map(|_| ())
        .map_err(|error| CliError::FileWrite {
            path: destination.to_owned(),
            error: error.error,
        })
}

fn write_expected(
    writer: &mut dyn Write,
    destination: &Utf8Path,
    expected: &[u8],
) -> Result<(), CliError> {
    writer
        .write_all(expected)
        .and_then(|()| writer.flush())
        .map_err(|error| CliError::FileWrite {
            path: destination.to_path_buf(),
            error,
        })
}

fn out_of_date(manifest: &Utf8Path, destination: &Utf8Path) -> CliError {
    CliError::EmbeddingBindingsOutOfDate {
        manifest: manifest.to_path_buf(),
        output: destination.to_path_buf(),
    }
}

#[cfg(test)]
mod tests {
    use super::{
        SyncOutcome, check, check_generated, program_path, sync, sync_generated,
        validate_generated, validate_generated_set, write_expected,
    };
    use crate::error::CliError;
    use camino::Utf8PathBuf;
    use std::fs;
    use std::io::{self, Write};
    use tempfile::tempdir;

    #[test]
    fn manages_both_files_and_removes_only_obsolete_owned_children() {
        let directory = tempdir().unwrap();
        let root = Utf8PathBuf::from_path_buf(directory.path().to_owned()).unwrap();
        let manifest = root.join("Cargo.toml");
        let destination = root.join("geam_bindings.rs");
        let child = program_path(&destination);
        let source = format!("{}\n// bindings\n", crate::embedding::GENERATED_HEADER);
        let program = format!(
            "{}\n// static program\n",
            crate::embedding::GENERATED_HEADER
        );
        validate_generated_set(&destination, false).unwrap();
        validate_generated_set(&destination, true).unwrap();
        assert_eq!(
            sync_generated(&destination, source.as_bytes(), Some(program.as_bytes())).unwrap(),
            SyncOutcome::Updated
        );
        assert_eq!(fs::read_to_string(&child).unwrap(), program);
        check_generated(
            &manifest,
            &destination,
            source.as_bytes(),
            Some(program.as_bytes()),
        )
        .unwrap();
        assert_eq!(
            sync_generated(&destination, source.as_bytes(), Some(program.as_bytes())).unwrap(),
            SyncOutcome::Unchanged
        );
        let sibling = child.with_file_name("handwritten.rs");
        fs::write(&sibling, "// user module\n").unwrap();
        assert!(
            matches!(check_generated(&manifest, &destination, source.as_bytes(), None), Err(CliError::EmbeddingBindingsOutOfDate { output, .. }) if output == child)
        );
        assert_eq!(
            sync_generated(&destination, source.as_bytes(), None).unwrap(),
            SyncOutcome::Updated
        );
        assert!(!child.exists());
        assert_eq!(fs::read_to_string(&sibling).unwrap(), "// user module\n");
        check_generated(&manifest, &destination, source.as_bytes(), None).unwrap();
        fs::write(&child, "// handwritten program\n").unwrap();
        check_generated(&manifest, &destination, source.as_bytes(), None).unwrap();
        assert_eq!(
            sync_generated(&destination, source.as_bytes(), None).unwrap(),
            SyncOutcome::Unchanged
        );
        assert!(
            matches!(sync_generated(&destination, source.as_bytes(), Some(program.as_bytes())), Err(CliError::EmbeddingFileConflict { path, .. }) if path == child)
        );
        assert_eq!(
            fs::read_to_string(&child).unwrap(),
            "// handwritten program\n"
        );
        assert_eq!(fs::read_to_string(&destination).unwrap(), source);
    }

    #[test]
    fn refreshes_crlf_generated_files_and_removes_obsolete_children() {
        let directory = tempdir().unwrap();
        let root = Utf8PathBuf::from_path_buf(directory.path().to_owned()).unwrap();
        let manifest = root.join("Cargo.toml");
        let destination = root.join("geam_bindings.rs");
        let child = program_path(&destination);
        let source = format!("{}\n// bindings\n", crate::embedding::GENERATED_HEADER);
        let program = format!("{}\n// program\n", crate::embedding::GENERATED_HEADER);
        fs::create_dir(destination.with_extension("")).unwrap();
        fs::write(&destination, source.replace('\n', "\r\n")).unwrap();
        fs::write(&child, program.replace('\n', "\r\n")).unwrap();

        validate_generated_set(&destination, true).unwrap();
        assert!(
            matches!(check_generated(&manifest, &destination, source.as_bytes(), Some(program.as_bytes())), Err(CliError::EmbeddingBindingsOutOfDate { output, .. }) if output == destination)
        );
        assert_eq!(
            sync_generated(&destination, source.as_bytes(), Some(program.as_bytes())).unwrap(),
            SyncOutcome::Updated
        );
        assert_eq!(fs::read(&destination).unwrap(), source.as_bytes());
        assert_eq!(fs::read(&child).unwrap(), program.as_bytes());
        check_generated(
            &manifest,
            &destination,
            source.as_bytes(),
            Some(program.as_bytes()),
        )
        .unwrap();
        assert_eq!(
            sync_generated(&destination, source.as_bytes(), Some(program.as_bytes())).unwrap(),
            SyncOutcome::Unchanged
        );

        fs::write(&child, program.replace('\n', "\r\n")).unwrap();
        let sibling = child.with_file_name("handwritten.rs");
        fs::write(&sibling, "// user module\r\n").unwrap();
        assert!(
            matches!(check_generated(&manifest, &destination, source.as_bytes(), None), Err(CliError::EmbeddingBindingsOutOfDate { output, .. }) if output == child)
        );
        assert_eq!(
            sync_generated(&destination, source.as_bytes(), None).unwrap(),
            SyncOutcome::Updated
        );
        assert!(!child.exists());
        assert_eq!(fs::read_to_string(&sibling).unwrap(), "// user module\r\n");
        assert_eq!(fs::read(&destination).unwrap(), source.as_bytes());
        check_generated(&manifest, &destination, source.as_bytes(), None).unwrap();
    }

    #[test]
    fn recovers_missing_and_stale_children_without_touching_a_fresh_root() {
        let directory = tempdir().unwrap();
        let root = Utf8PathBuf::from_path_buf(directory.path().to_owned()).unwrap();
        let manifest = root.join("Cargo.toml");
        let destination = root.join("geam_bindings.rs");
        let child = program_path(&destination);
        let source = format!("{}\n// bindings\n", crate::embedding::GENERATED_HEADER);
        let program = format!("{}\n// program\n", crate::embedding::GENERATED_HEADER);
        sync_generated(&destination, source.as_bytes(), None).unwrap();
        let modified = fs::metadata(&destination).unwrap().modified().unwrap();
        assert!(
            matches!(check_generated(&manifest, &destination, source.as_bytes(), Some(program.as_bytes())), Err(CliError::EmbeddingBindingsOutOfDate { output, .. }) if output == child)
        );
        assert_eq!(
            sync_generated(&destination, source.as_bytes(), Some(program.as_bytes())).unwrap(),
            SyncOutcome::Updated
        );
        let changed = format!("{program}// changed body\n");
        assert!(
            check_generated(
                &manifest,
                &destination,
                source.as_bytes(),
                Some(changed.as_bytes())
            )
            .is_err()
        );
        assert_eq!(fs::read_to_string(&child).unwrap(), program);
        assert_eq!(
            sync_generated(&destination, source.as_bytes(), Some(changed.as_bytes())).unwrap(),
            SyncOutcome::Updated
        );
        check_generated(
            &manifest,
            &destination,
            source.as_bytes(),
            Some(changed.as_bytes()),
        )
        .unwrap();
        assert_eq!(
            fs::metadata(&destination).unwrap().modified().unwrap(),
            modified
        );
    }

    #[test]
    fn rejects_non_directory_prepared_output_before_replacing_bindings() {
        let directory = tempdir().unwrap();
        let root = Utf8PathBuf::from_path_buf(directory.path().to_owned()).unwrap();
        let destination = root.join("geam_bindings.rs");
        let child_directory = destination.with_extension("");
        fs::write(&child_directory, "user file").unwrap();
        validate_generated_set(&destination, false).unwrap();
        assert!(
            matches!(validate_generated_set(&destination, true), Err(CliError::EmbeddingFileConflict { path, .. }) if path == child_directory)
        );
        assert!(!destination.exists());
        assert!(!super::obsolete_program(&destination).unwrap());
        fs::remove_file(&child_directory).unwrap();
        fs::create_dir(&child_directory).unwrap();
        fs::create_dir(program_path(&destination)).unwrap();
        assert!(matches!(
            super::obsolete_program(&destination).unwrap_err(),
            CliError::FileRead { path, .. } if path == program_path(&destination)
        ));
        assert!(matches!(
            validate_generated_set(&destination, true).unwrap_err(),
            CliError::FileRead { path, .. } if path == program_path(&destination)
        ));
    }

    #[cfg(unix)]
    #[test]
    fn never_writes_prepared_data_through_a_symlinked_child_directory() {
        let directory = tempdir().unwrap();
        let root = Utf8PathBuf::from_path_buf(directory.path().to_owned()).unwrap();
        let destination = root.join("geam_bindings.rs");
        let unrelated = root.join("unrelated");
        fs::create_dir(&unrelated).unwrap();
        std::os::unix::fs::symlink(&unrelated, destination.with_extension("")).unwrap();
        assert!(matches!(
            validate_generated_set(&destination, true).unwrap_err(),
            CliError::EmbeddingFileConflict { path, .. } if path == destination.with_extension("")
        ));
        assert!(!super::obsolete_program(&destination).unwrap());
        assert_eq!(fs::read_dir(unrelated).unwrap().count(), 0);
    }

    #[test]
    fn permits_only_missing_or_marked_generated_files_for_replacement() {
        let directory = tempdir().expect("temporary directory");
        let root = Utf8PathBuf::from_path_buf(directory.path().to_owned()).expect("UTF-8 fixture");
        let destination = root.join("geam_bindings.rs");
        validate_generated(&destination).expect("missing generated file");
        fs::write(&destination, "// handwritten Rust\n").expect("user module");
        assert_eq!(
            validate_generated(&destination)
                .expect_err("user-owned module")
                .to_string(),
            format!(
                "refusing to replace existing embedding file {destination}: the file was not generated by geam embedding sync"
            )
        );
        let marker = crate::embedding::GENERATED_HEADER.trim_end_matches('\n');
        for suffix in ["", "\r", " extra\n"] {
            fs::write(&destination, format!("{marker}{suffix}")).unwrap();
            assert_eq!(
                validate_generated(&destination).unwrap_err().to_string(),
                format!(
                    "refusing to replace existing embedding file {destination}: the file was not generated by geam embedding sync"
                )
            );
        }
        fs::write(
            &destination,
            "// Generated by `geam embedding sync`. Do not edit.\n\n// old bindings\n",
        )
        .expect("generated module");
        validate_generated(&destination).expect("marked generated module");
        let unreadable = root.join("directory");
        fs::create_dir(&unreadable).expect("conflicting directory");
        assert!(
            matches!(validate_generated(&unreadable), Err(CliError::FileRead { path, .. }) if path == unreadable)
        );
    }

    #[cfg(unix)]
    #[test]
    fn preserves_the_generated_set_when_child_reads_or_writes_fail() {
        use std::os::unix::fs::PermissionsExt;
        let directory = tempdir().unwrap();
        let root = Utf8PathBuf::from_path_buf(directory.path().to_owned()).unwrap();
        let manifest = root.join("Cargo.toml");
        let destination = root.join("bindings.rs");
        let child = program_path(&destination);
        let source = format!("{}\n", crate::embedding::GENERATED_HEADER);
        fs::write(&destination, &source).unwrap();
        fs::set_permissions(&root, fs::Permissions::from_mode(0o500)).unwrap();
        let result = sync_generated(&destination, source.as_bytes(), Some(source.as_bytes()));
        fs::set_permissions(&root, fs::Permissions::from_mode(0o700)).unwrap();
        assert!(
            matches!(result.unwrap_err(), CliError::FileWrite { path, .. } if path == child.with_file_name(""))
        );
        assert_eq!(fs::read_to_string(&destination).unwrap(), source);
        fs::create_dir_all(&child).unwrap();
        assert!(
            matches!(check_generated(&manifest, &destination, source.as_bytes(), None), Err(CliError::FileRead { path, .. }) if path == child)
        );
        assert!(
            matches!(sync_generated(&destination, source.as_bytes(), None), Err(CliError::FileRead { path, .. }) if path == child)
        );
        fs::remove_dir(&child).unwrap();
        fs::write(&child, &source).unwrap();
        let children = child.with_file_name("");
        fs::set_permissions(&children, fs::Permissions::from_mode(0o500)).unwrap();
        let result = sync_generated(&destination, source.as_bytes(), None);
        fs::set_permissions(&children, fs::Permissions::from_mode(0o700)).unwrap();
        assert!(matches!(result.unwrap_err(), CliError::FileWrite { path, .. } if path == child));
        assert_eq!(fs::read_to_string(&child).unwrap(), source);

        fs::set_permissions(&root, fs::Permissions::from_mode(0o000)).unwrap();
        let validation = validate_generated_set(&destination, true);
        let obsolete = super::obsolete_program(&destination);
        fs::set_permissions(&root, fs::Permissions::from_mode(0o700)).unwrap();
        assert!(
            matches!(validation.unwrap_err(), CliError::FileRead { path, .. } if path == children)
        );
        assert!(
            matches!(obsolete.unwrap_err(), CliError::FileRead { path, .. } if path == children)
        );
    }

    #[cfg(unix)]
    #[test]
    fn reports_access_changes_between_staging_and_publication() {
        use std::os::unix::fs::PermissionsExt;
        let directory = tempdir().unwrap();
        let root = Utf8PathBuf::from_path_buf(directory.path().to_owned()).unwrap();
        let destination = root.join("bindings.rs");
        let child = program_path(&destination);
        let source = format!("{}\n", crate::embedding::GENERATED_HEADER);
        fs::create_dir_all(child.with_file_name("")).unwrap();
        for block_child in [true, false] {
            let parent = if block_child {
                child.with_file_name("")
            } else {
                root.clone()
            };
            let staged_root = super::stage(&destination, source.as_bytes()).unwrap();
            let staged_child = super::stage(&child, source.as_bytes()).unwrap();
            fs::set_permissions(&parent, fs::Permissions::from_mode(0o500)).unwrap();
            let result = super::publish_generated(&destination, staged_root, staged_child, false);
            fs::set_permissions(&parent, fs::Permissions::from_mode(0o700)).unwrap();
            let error = result.unwrap_err();
            let expected = if block_child { &child } else { &destination };
            assert!(matches!(error, CliError::FileWrite { path, .. } if path == *expected));
            assert!(!destination.exists());
        }
        sync_generated(&destination, source.as_bytes(), Some(source.as_bytes())).unwrap();
        let parent = child.with_file_name("");
        fs::set_permissions(&parent, fs::Permissions::from_mode(0o500)).unwrap();
        let result = sync_generated(
            &destination,
            source.as_bytes(),
            Some(format!("{source}// new\n").as_bytes()),
        );
        fs::set_permissions(&parent, fs::Permissions::from_mode(0o700)).unwrap();
        let error = result.unwrap_err();
        assert!(matches!(error, CliError::FileWrite { path, .. } if path == child));
    }

    #[test]
    fn leaves_identical_output_untouched_and_atomically_replaces_changes() {
        let directory = tempdir().expect("temporary directory should be created");
        let root = Utf8PathBuf::from_path_buf(directory.path().to_path_buf())
            .expect("temporary path should be valid UTF-8");
        let destination = root.join("geam_bindings.rs");
        fs::write(&destination, "same").expect("fixture output should be written");
        #[cfg(unix)]
        let original_inode = std::os::unix::fs::MetadataExt::ino(
            &fs::metadata(&destination).expect("fixture metadata should be readable"),
        );

        assert_eq!(
            sync(&root, &destination, b"same").expect("identical output should succeed"),
            SyncOutcome::Unchanged,
        );
        #[cfg(unix)]
        assert_eq!(
            std::os::unix::fs::MetadataExt::ino(
                &fs::metadata(&destination).expect("unchanged metadata should be readable"),
            ),
            original_inode,
        );

        assert_eq!(
            sync(&root, &destination, b"changed").expect("changed output should succeed"),
            SyncOutcome::Updated,
        );
        assert_eq!(
            fs::read(&destination).expect("updated output should be readable"),
            b"changed",
        );
        #[cfg(unix)]
        assert_ne!(
            std::os::unix::fs::MetadataExt::ino(
                &fs::metadata(&destination).expect("updated metadata should be readable"),
            ),
            original_inode,
        );
    }

    #[test]
    fn checks_exact_missing_and_stale_bytes_without_writing() {
        let directory = tempdir().expect("temporary directory should be created");
        let root = Utf8PathBuf::from_path_buf(directory.path().to_path_buf())
            .expect("temporary path should be valid UTF-8");
        let manifest = root.join("Cargo.toml");
        let destination = root.join("geam_bindings.rs");

        let missing = check(&manifest, &destination, b"expected")
            .expect_err("missing output should fail checking");
        assert!(matches!(
            missing,
            CliError::EmbeddingBindingsOutOfDate { manifest: path, output }
                if path == manifest && output == destination
        ));
        assert!(!destination.exists());

        fs::write(&destination, b"stale\r\n").expect("stale output should be written");
        let stale_metadata = fs::metadata(&destination).expect("stale metadata should be readable");
        let stale = check(&manifest, &destination, b"expected\n")
            .expect_err("byte-stale output should fail checking");
        assert!(matches!(
            stale,
            CliError::EmbeddingBindingsOutOfDate { manifest: path, output }
                if path == manifest && output == destination
        ));
        assert_eq!(
            fs::read(&destination).expect("stale output should remain readable"),
            b"stale\r\n",
        );
        assert_eq!(
            fs::metadata(&destination)
                .expect("checked metadata should be readable")
                .permissions(),
            stale_metadata.permissions(),
        );

        fs::write(&destination, b"expected\n").expect("exact output should be written");
        let exact_metadata = fs::metadata(&destination).expect("exact metadata should be readable");
        let modified = exact_metadata
            .modified()
            .expect("exact modification time should be readable");
        #[cfg(unix)]
        let inode = std::os::unix::fs::MetadataExt::ino(&exact_metadata);
        check(&manifest, &destination, b"expected\n").expect("exact output should pass checking");
        let checked_metadata =
            fs::metadata(&destination).expect("checked exact metadata should be readable");
        assert_eq!(
            fs::read(&destination).expect("checked exact output should remain readable"),
            b"expected\n",
        );
        assert_eq!(checked_metadata.permissions(), exact_metadata.permissions());
        assert_eq!(
            checked_metadata
                .modified()
                .expect("checked modification time should be readable"),
            modified,
        );
        #[cfg(unix)]
        assert_eq!(
            std::os::unix::fs::MetadataExt::ino(&checked_metadata),
            inode,
        );
    }

    #[test]
    fn preserves_check_read_failures_with_destination_context() {
        let directory = tempdir().expect("temporary directory should be created");
        let root = Utf8PathBuf::from_path_buf(directory.path().to_path_buf())
            .expect("temporary path should be valid UTF-8");
        let manifest = root.join("Cargo.toml");
        let destination = root.join("geam_bindings.rs");
        fs::create_dir(&destination).expect("directory fixture should be created");

        let error = check(&manifest, &destination, b"expected")
            .expect_err("unreadable checked output should fail");
        assert!(matches!(
            error,
            CliError::FileRead { path, .. } if path == destination
        ));
        assert!(destination.is_dir());
    }

    #[test]
    fn preserves_read_failures_with_destination_context() {
        let directory = tempdir().expect("temporary directory should be created");
        let root = Utf8PathBuf::from_path_buf(directory.path().to_path_buf())
            .expect("temporary path should be valid UTF-8");
        let destination = root.join("geam_bindings.rs");
        fs::create_dir(&destination).expect("directory fixture should be created");

        let error =
            sync(&root, &destination, b"expected").expect_err("unreadable destination should fail");
        assert!(matches!(
            error,
            CliError::FileRead { path, .. } if path == destination
        ));
        assert!(destination.is_dir());
    }

    #[test]
    fn preserves_write_failures_with_destination_context() {
        let directory = tempdir().expect("temporary directory should be created");
        let root = Utf8PathBuf::from_path_buf(directory.path().to_path_buf())
            .expect("temporary path should be valid UTF-8");
        let missing_directory = root.join("missing");
        let destination = missing_directory.join("geam_bindings.rs");

        let error = sync(&missing_directory, &destination, b"expected")
            .expect_err("missing output directory should fail");
        assert!(matches!(
            error,
            CliError::FileWrite { path, error }
                if path == destination && error.kind() == std::io::ErrorKind::NotFound
        ));
        assert!(!destination.exists());
    }

    #[test]
    fn preserves_content_write_and_flush_failures_with_destination_context() {
        enum Failure {
            Write,
            Flush,
        }

        struct FailingWriter(Failure);

        impl Write for FailingWriter {
            fn write(&mut self, buffer: &[u8]) -> io::Result<usize> {
                match self.0 {
                    Failure::Write => Err(io::Error::other("fixture write failure")),
                    Failure::Flush => Ok(buffer.len()),
                }
            }

            fn flush(&mut self) -> io::Result<()> {
                Err(io::Error::other("fixture flush failure"))
            }
        }

        let destination = Utf8PathBuf::from("/workspace/src/geam_bindings.rs");
        for failure in [Failure::Write, Failure::Flush] {
            let error = write_expected(&mut FailingWriter(failure), &destination, b"expected")
                .expect_err("content output failure should be preserved");
            assert!(matches!(
                error,
                CliError::FileWrite { path, error }
                    if path == destination && error.kind() == io::ErrorKind::Other
            ));
        }
    }

    #[test]
    fn preserves_atomic_persist_failures_with_destination_context() {
        let directory = tempdir().expect("temporary directory should be created");
        let root = Utf8PathBuf::from_path_buf(directory.path().to_path_buf())
            .expect("temporary path should be valid UTF-8");
        let destination = root.join("missing/geam_bindings.rs");

        let error = sync(&root, &destination, b"expected")
            .expect_err("missing destination parent should reject persistence");
        assert!(matches!(
            error,
            CliError::FileWrite { path, error }
                if path == destination && error.kind() == io::ErrorKind::NotFound
        ));
        assert!(!destination.exists());
    }

    #[cfg(unix)]
    #[test]
    fn preserves_previous_output_when_atomic_replacement_cannot_start() {
        use std::os::unix::fs::PermissionsExt;

        let directory = tempdir().expect("temporary directory should be created");
        let root = Utf8PathBuf::from_path_buf(directory.path().to_path_buf())
            .expect("temporary path should be valid UTF-8");
        let destination = root.join("geam_bindings.rs");
        fs::write(&destination, "previous").expect("previous output should be written");
        fs::set_permissions(&root, fs::Permissions::from_mode(0o500))
            .expect("output directory should become read-only");

        let result = sync(&root, &destination, b"changed");
        fs::set_permissions(&root, fs::Permissions::from_mode(0o700))
            .expect("output directory permissions should be restored");

        let error = result.expect_err("read-only output directory should reject replacement");
        assert!(matches!(
            error,
            CliError::FileWrite { path, error }
                if path == destination
                    && error.kind() == std::io::ErrorKind::PermissionDenied
        ));
        assert_eq!(
            fs::read(&destination).expect("previous output should remain readable"),
            b"previous",
        );
    }
}
