use super::boundary::{FunctionBinding, PlainBindings, Scalar};
use std::collections::BTreeSet;

pub(super) fn plain(bindings: &PlainBindings) -> String {
    let mut output = String::from("// Generated by `geam embedding sync`. Do not edit.\n\n");
    let alias = bindings.geam_alias.as_str();
    let mut imports = BTreeSet::from([
        "BindingError",
        "Function",
        "FunctionDeclaration",
        "ModuleBindings",
        "ModuleBuilder",
    ]);
    for function in bindings.functions() {
        imports.extend(
            function
                .arguments
                .iter()
                .chain(std::iter::once(&function.return_type))
                .filter_map(Scalar::import),
        );
    }
    for import in imports {
        output.push_str(&format!("use {alias}::embedding::{import};\n"));
    }
    output.push_str(&format!(
        "\npub const ROOT_MODULE: &str = {:?};\n\n",
        bindings.root_module
    ));
    output.push_str("pub struct Functions {\n");
    for function in bindings.functions() {
        push_function_field(&mut output, function);
    }
    output.push_str("}\n\n");
    output.push_str(
        "pub fn bind(builder: ModuleBuilder) -> Result<(ModuleBindings, Functions), BindingError> {\n",
    );
    let first = &bindings.first;
    let mutability = if bindings.remaining.is_empty() {
        ""
    } else {
        "mut "
    };
    push_binding(
        &mut output,
        &format!("({mutability}bindings, function_0)"),
        "builder",
        first,
    );
    for (index, function) in bindings.remaining.iter().enumerate() {
        push_binding(
            &mut output,
            &format!("function_{}", index + 1),
            "bindings",
            function,
        );
    }
    let fields = bindings
        .functions()
        .enumerate()
        .map(|(index, function)| format!("{}: function_{index}", function.rust_name.as_str()))
        .collect::<Vec<_>>();
    let result = format!(
        "    Ok((bindings, Functions {{ {} }}))\n",
        fields.join(", ")
    );
    if result.trim_end().len() <= 100 {
        output.push_str(&result);
    } else {
        output.push_str("    Ok((\n        bindings,\n        Functions {\n");
        for field in fields {
            output.push_str(&format!("            {field},\n"));
        }
        output.push_str("        },\n    ))\n");
    }
    output.push_str("}\n");
    output
}

fn push_function_field(output: &mut String, function: &FunctionBinding) {
    let arguments = argument_tuple(&function.arguments);
    let return_type = function.return_type.rust_type();
    let prefix = format!("    pub {}:", function.rust_name.as_str());
    let type_ = format!("Function<{arguments}, {return_type}>");
    let line = format!("{prefix} {type_},\n");
    if line.trim_end().len() <= 100 {
        output.push_str(&line);
    } else if 8 + type_.len() < 100 {
        output.push_str(&format!("{prefix}\n        {type_},\n"));
    } else {
        let (function_indent, content_indent, item_indent) =
            if prefix.len() + " Function<".len() <= 100 {
                output.push_str(&format!("{prefix} Function<\n        (\n"));
                ("    ", "        ", "            ")
            } else {
                output.push_str(&format!("{prefix}\n        Function<\n            (\n"));
                ("        ", "            ", "                ")
            };
        for argument in &function.arguments {
            output.push_str(&format!("{item_indent}{},\n", argument.rust_type()));
        }
        output.push_str(&format!(
            "{content_indent}),\n{content_indent}{return_type},\n{function_indent}>,\n"
        ));
    }
}

fn push_binding(output: &mut String, pattern: &str, owner: &str, function: &FunctionBinding) {
    let statement = format!(
        "    let {pattern} = {owner}.function(FunctionDeclaration::new({:?}))?;\n",
        function.gleam_name
    );
    if statement.trim_end().len() <= 100 {
        output.push_str(&statement);
    } else {
        output.push_str(&format!(
            "    let {pattern} =\n        {owner}.function(FunctionDeclaration::new({:?}))?;\n",
            function.gleam_name
        ));
    }
}

fn argument_tuple(arguments: &[Scalar]) -> String {
    match arguments {
        [] => "()".to_owned(),
        [argument] => format!("({},)", argument.rust_type()),
        arguments => format!(
            "({})",
            arguments
                .iter()
                .map(Scalar::rust_type)
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

impl Scalar {
    fn import(&self) -> Option<&'static str> {
        match self {
            Self::Int => Some("BigInt"),
            Self::String => Some("EcoString"),
            Self::BitArray => Some("BitArrayValue"),
            Self::Float | Self::UtfCodepoint | Self::Bool | Self::Nil => None,
        }
    }

    fn rust_type(&self) -> &'static str {
        match self {
            Self::Int => "BigInt",
            Self::Float => "f64",
            Self::String => "EcoString",
            Self::BitArray => "BitArrayValue",
            Self::UtfCodepoint => "char",
            Self::Bool => "bool",
            Self::Nil => "()",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{plain, push_function_field};
    use crate::embedding::boundary::{FunctionBinding, PlainBindings, Scalar};
    use crate::embedding::identifier::RustIdentifier;
    use std::fs;
    use std::process::Command;

    #[test]
    fn renders_deterministic_plain_bindings_for_all_scalar_paths() {
        let bindings = PlainBindings {
            geam_alias: RustIdentifier::parse("runtime")
                .expect("fixture crate alias should be valid"),
            root_module: "inventory_rules".to_owned(),
            first: FunctionBinding {
                gleam_name: "async".to_owned(),
                rust_name: RustIdentifier::parse("async")
                    .expect("keyword should use a raw identifier"),
                arguments: Vec::new(),
                return_type: Scalar::Nil,
            },
            remaining: vec![FunctionBinding {
                gleam_name: "all_values".to_owned(),
                rust_name: RustIdentifier::parse("all_values")
                    .expect("fixture function should be valid"),
                arguments: vec![
                    Scalar::Int,
                    Scalar::Float,
                    Scalar::String,
                    Scalar::BitArray,
                    Scalar::UtfCodepoint,
                    Scalar::Bool,
                    Scalar::Nil,
                ],
                return_type: Scalar::String,
            }],
        };

        let source = plain(&bindings);
        assert_eq!(
            source,
            r#"// Generated by `geam embedding sync`. Do not edit.

use runtime::embedding::BigInt;
use runtime::embedding::BindingError;
use runtime::embedding::BitArrayValue;
use runtime::embedding::EcoString;
use runtime::embedding::Function;
use runtime::embedding::FunctionDeclaration;
use runtime::embedding::ModuleBindings;
use runtime::embedding::ModuleBuilder;

pub const ROOT_MODULE: &str = "inventory_rules";

pub struct Functions {
    pub r#async: Function<(), ()>,
    pub all_values: Function<(BigInt, f64, EcoString, BitArrayValue, char, bool, ()), EcoString>,
}

pub fn bind(builder: ModuleBuilder) -> Result<(ModuleBindings, Functions), BindingError> {
    let (mut bindings, function_0) = builder.function(FunctionDeclaration::new("async"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("all_values"))?;
    Ok((bindings, Functions { r#async: function_0, all_values: function_1 }))
}
"#,
        );
        assert_eq!(plain(&bindings), source);
    }

    #[test]
    fn keeps_long_representable_identifiers_rustfmt_stable() {
        let name = "function_with_a_deliberately_long_but_representable_name_that_remains_part_of_the_public_boundary";
        let bindings = PlainBindings {
            geam_alias: RustIdentifier::parse("runtime")
                .expect("fixture crate alias should be valid"),
            root_module: "boundary".to_owned(),
            first: FunctionBinding {
                gleam_name: name.to_owned(),
                rust_name: RustIdentifier::parse(name)
                    .expect("long identifier should remain representable"),
                arguments: vec![
                    Scalar::Int,
                    Scalar::Float,
                    Scalar::String,
                    Scalar::BitArray,
                    Scalar::UtfCodepoint,
                    Scalar::Bool,
                    Scalar::Nil,
                ],
                return_type: Scalar::String,
            },
            remaining: Vec::new(),
        };
        let directory = tempfile::tempdir().expect("temporary directory should be created");
        let path = directory.path().join("geam_bindings.rs");
        fs::write(&path, plain(&bindings)).expect("generated source should be written");
        let output = Command::new("rustfmt")
            .arg("--check")
            .arg(&path)
            .output()
            .expect("rustfmt should start");
        let stdout = String::from_utf8_lossy(&output.stdout);

        assert!(
            output.status.success(),
            "long generated source should already be formatted:\n{stdout}",
        );
    }

    #[test]
    fn renders_the_longest_scalar_function_field_exactly() {
        let short = FunctionBinding {
            gleam_name: "all_bits".to_owned(),
            rust_name: RustIdentifier::parse("all_bits").expect("fixture function should be valid"),
            arguments: vec![Scalar::BitArray; 7],
            return_type: Scalar::BitArray,
        };
        let long_name = "function_with_a_deliberately_long_but_representable_name_that_remains_part_of_the_public_boundary";
        let long = FunctionBinding {
            gleam_name: long_name.to_owned(),
            rust_name: RustIdentifier::parse(long_name)
                .expect("long fixture function should be valid"),
            arguments: vec![Scalar::BitArray; 7],
            return_type: Scalar::BitArray,
        };
        let mut field = String::new();

        push_function_field(&mut field, &short);
        push_function_field(&mut field, &long);

        assert_eq!(
            field,
            r#"    pub all_bits: Function<
        (
            BitArrayValue,
            BitArrayValue,
            BitArrayValue,
            BitArrayValue,
            BitArrayValue,
            BitArrayValue,
            BitArrayValue,
        ),
        BitArrayValue,
    >,
    pub function_with_a_deliberately_long_but_representable_name_that_remains_part_of_the_public_boundary:
        Function<
            (
                BitArrayValue,
                BitArrayValue,
                BitArrayValue,
                BitArrayValue,
                BitArrayValue,
                BitArrayValue,
                BitArrayValue,
            ),
            BitArrayValue,
        >,
"#,
        );
        let directory = tempfile::tempdir().expect("temporary directory should be created");
        let path = directory.path().join("geam_bindings.rs");
        fs::write(&path, format!("pub struct Functions {{\n{field}}}\n"))
            .expect("long scalar field should be written");
        let status = Command::new("rustfmt")
            .arg("--check")
            .arg(&path)
            .status()
            .expect("rustfmt should start");
        assert!(status.success());
    }
}
