use super::boundary::{FunctionBinding, PlainBindings, Scalar};
use super::profile::{ComponentBinding, HostedBindings, HostedCapabilities, HostedComponents};
use std::collections::BTreeSet;

pub(super) fn plain(bindings: &PlainBindings) -> String {
    let mut output = String::from("// Generated by `geam embedding sync`. Do not edit.\n\n");
    let alias = bindings.geam_alias.as_str();
    let mut imports = BTreeSet::from([
        "BindingError",
        "Function",
        "FunctionDeclaration",
        "ModuleBindings",
        "ModuleBuilder",
    ]);
    for function in bindings.functions() {
        imports.extend(
            function
                .arguments
                .iter()
                .chain(std::iter::once(&function.return_type))
                .filter_map(Scalar::import),
        );
    }
    for import in imports {
        output.push_str(&format!("use {alias}::embedding::{import};\n"));
    }
    output.push_str(&format!(
        "\npub const ROOT_MODULE: &str = {:?};\n\n",
        bindings.root_module
    ));
    output.push_str("pub struct Functions {\n");
    for function in bindings.functions() {
        push_function_field(&mut output, function);
    }
    output.push_str("}\n\n");
    output.push_str(
        "pub fn bind(builder: ModuleBuilder) -> Result<(ModuleBindings, Functions), BindingError> {\n",
    );
    let first = &bindings.first;
    let mutability = if bindings.remaining.is_empty() {
        ""
    } else {
        "mut "
    };
    push_binding(
        &mut output,
        &format!("({mutability}bindings, function_0)"),
        "builder",
        first,
    );
    for (index, function) in bindings.remaining.iter().enumerate() {
        push_binding(
            &mut output,
            &format!("function_{}", index + 1),
            "bindings",
            function,
        );
    }
    let fields = bindings
        .functions()
        .enumerate()
        .map(|(index, function)| format!("{}: function_{index}", function.rust_name.as_str()))
        .collect::<Vec<_>>();
    let result = format!(
        "    Ok((bindings, Functions {{ {} }}))\n",
        fields.join(", ")
    );
    if result.trim_end().len() <= 100 {
        output.push_str(&result);
    } else {
        output.push_str("    Ok((\n        bindings,\n        Functions {\n");
        for field in fields {
            output.push_str(&format!("            {field},\n"));
        }
        output.push_str("        },\n    ))\n");
    }
    output.push_str("}\n");
    output
}

pub(super) fn hosted(bindings: &HostedBindings) -> String {
    let mut output = String::from("// Generated by `geam embedding sync`. Do not edit.\n\n");
    let boundary = &bindings.boundary;
    let alias = boundary.geam_alias.as_str();
    let components = &bindings.components;
    let mut host_imports = BTreeSet::from([
        "HostComponentProfile",
        "HostModule",
        "HostProfile",
        "HostProviderComponent",
        "HostProviderComponentRegistration",
        "HostProviderSet",
        "HostRegistrationError",
    ]);
    if components.has_external() {
        host_imports.extend([
            "HostProviderComponentInitialization",
            "HostProviderConfiguration",
            "HostProviderInitializationError",
        ]);
    }
    for import in host_imports {
        output.push_str(&format!("use {alias}::{import};\n"));
    }
    output.push('\n');
    let mut embedding_imports = BTreeSet::from([
        "BindingError",
        "Function",
        "FunctionDeclaration",
        "HostedModuleBindings",
        "HostedModuleBuilder",
    ]);
    for function in boundary.functions() {
        embedding_imports.extend(
            function
                .arguments
                .iter()
                .chain(std::iter::once(&function.return_type))
                .filter_map(Scalar::import),
        );
    }
    for import in embedding_imports {
        output.push_str(&format!("use {alias}::embedding::{import};\n"));
    }
    if components.has_stdlib() || components.has_time() {
        output.push_str("use std::marker::PhantomData;\n");
    }

    output.push_str(&format!(
        "\npub const ROOT_MODULE: &str = {:?};\n\n",
        boundary.root_module
    ));
    push_profile_declaration(&mut output, components);
    push_provider_set_alias(&mut output, components);
    push_stores(&mut output, alias, components);
    push_configurations(&mut output, components);
    push_run_state(&mut output, alias, components);
    push_host_profile(&mut output, alias, components);
    for component in components.iter() {
        push_component_profile(&mut output, alias, components, component);
    }
    if components.has_stdlib() {
        push_stdlib_profile(&mut output, alias, components);
    }
    if components.has_time() {
        push_time_profile(&mut output, alias, components);
    }
    push_host_providers(&mut output, alias, components);

    output.push_str("pub struct Functions {\n");
    for function in boundary.functions() {
        push_function_field(&mut output, function);
    }
    output.push_str("}\n\n");
    push_hosted_bind(&mut output, alias, components, boundary);
    output
}

fn push_provider_set_alias(output: &mut String, components: &HostedComponents) {
    output.push_str(&format!(
        "pub type ProviderSet{} = HostProviderSet<{}>;\n\n",
        generics(components),
        profile_type(components),
    ));
}

fn push_profile_declaration(output: &mut String, components: &HostedComponents) {
    match components.capabilities() {
        HostedCapabilities::None => output.push_str("pub struct Profile;\n\n"),
        HostedCapabilities::Io => {
            output.push_str("pub struct Profile<Io>(PhantomData<fn() -> Io>);\n\n")
        }
        HostedCapabilities::IoAndTime => output
            .push_str("pub struct Profile<Io, Source>(PhantomData<fn() -> (Io, Source)>);\n\n"),
    }
}

fn push_stores(output: &mut String, alias: &str, components: &HostedComponents) {
    output.push_str(&format!("pub struct Stores{}", generics(components)));
    push_bounds_open(output, alias, components);
    for component in components.iter() {
        push_component_field(output, alias, component, "Stores");
    }
    output.push_str("}\n\n");

    output.push_str(&format!(
        "impl{} Default for Stores{}",
        generics(components),
        generics(components),
    ));
    push_bounds_open(output, alias, components);
    output.push_str("    fn default() -> Self {\n        Self {\n");
    for component in components.iter() {
        let value = if component == &ComponentBinding::Time {
            "()"
        } else {
            "Default::default()"
        };
        output.push_str(&format!(
            "            {}: {value},\n",
            component_field(component),
        ));
    }
    output.push_str("        }\n    }\n}\n\n");
}

fn push_configurations(output: &mut String, components: &HostedComponents) {
    let external = components
        .iter()
        .filter_map(|component| match component {
            ComponentBinding::External(component) => Some(component),
            ComponentBinding::Stdlib | ComponentBinding::Json | ComponentBinding::Time => None,
        })
        .collect::<Vec<_>>();
    if external.is_empty() {
        output.push_str("pub struct ProviderConfigurations;\n\n");
        return;
    }
    output.push_str("pub struct ProviderConfigurations {\n");
    for component in external {
        output.push_str(&format!(
            "    pub {}: HostProviderConfiguration,\n",
            component.configuration_field.as_str(),
        ));
    }
    output.push_str("}\n\n");
}

fn push_run_state(output: &mut String, alias: &str, components: &HostedComponents) {
    output.push_str(&format!("pub struct RunState{}", generics(components)));
    push_bounds_open(output, alias, components);
    for component in components.iter() {
        push_component_field(output, alias, component, "RunState");
    }
    output.push_str("}\n\n");

    output.push_str(&format!(
        "impl{} RunState{}",
        generics(components),
        generics(components),
    ));
    push_bounds_open(output, alias, components);
    output.push_str("    pub fn initialize(\n");
    if components.has_stdlib() {
        output.push_str(&format!(
            "        stdlib: {alias}::gleam_stdlib::GleamStdlibRunState<Io>,\n"
        ));
    }
    if components.has_time() {
        output.push_str("        time: Source,\n");
    }
    let configurations = if components.has_external() {
        "configurations"
    } else {
        "_configurations"
    };
    output.push_str(&format!(
        "        {configurations}: ProviderConfigurations,\n    )"
    ));
    let compact_state = components
        .iter()
        .map(|component| match component {
            ComponentBinding::Stdlib => Some("stdlib"),
            ComponentBinding::Json => Some("json: ()"),
            ComponentBinding::Time => Some("time"),
            ComponentBinding::External(_) => None,
        })
        .collect::<Option<Vec<_>>>()
        .map(|fields| fields.join(", "))
        .filter(|fields| fields.len() <= 18);
    if components.has_external() {
        output.push_str(" -> Result<Self, HostProviderInitializationError> {\n        Ok(Self {\n");
    } else if let Some(fields) = &compact_state {
        output.push_str(&format!(" -> Self {{\n        Self {{ {fields} }}\n"));
    } else {
        output.push_str(" -> Self {\n        Self {\n");
    }
    if compact_state.is_none() {
        for component in components.iter() {
            match component {
                ComponentBinding::Stdlib => output.push_str("            stdlib,\n"),
                ComponentBinding::Json => output.push_str("            json: (),\n"),
                ComponentBinding::Time => output.push_str("            time,\n"),
                ComponentBinding::External(component) => {
                    push_external_initialization(output, alias, component)
                }
            }
        }
    }
    if components.has_external() {
        output.push_str("        })\n    }\n");
    } else if compact_state.is_some() {
        output.push_str("    }\n");
    } else {
        output.push_str("        }\n    }\n");
    }
    if components.has_stdlib() {
        output.push_str(&format!(
            "\n    pub fn stdlib(&self) -> &{alias}::gleam_stdlib::GleamStdlibRunState<Io> {{\n        &self.stdlib\n    }}\n\n    pub fn stdlib_mut(&mut self) -> &mut {alias}::gleam_stdlib::GleamStdlibRunState<Io> {{\n        &mut self.stdlib\n    }}\n"
        ));
    }
    output.push_str("}\n\n");
}

fn push_host_profile(output: &mut String, alias: &str, components: &HostedComponents) {
    let profile = profile_type(components);
    output.push_str(&format!(
        "impl{} HostProfile for {profile}",
        generics(components),
    ));
    push_bounds_open(output, alias, components);
    output.push_str(&format!(
        "    type ExternalStores = Stores{};\n    type RunState = RunState{};\n}}\n\n",
        generics(components),
        generics(components),
    ));
}

fn push_component_profile(
    output: &mut String,
    alias: &str,
    components: &HostedComponents,
    component: &ComponentBinding,
) {
    let component_type = component_type(alias, component);
    let field = component_field(component);
    let implementation = format!(
        "impl{} HostComponentProfile<{component_type}> for {}",
        generics(components),
        profile_type(components),
    );
    if implementation.len() <= 100 {
        output.push_str(&implementation);
    } else {
        output.push_str(&format!(
            "impl{} HostComponentProfile<{component_type}>\n    for {}",
            generics(components),
            profile_type(components),
        ));
    }
    push_bounds_open(output, alias, components);
    output.push_str("    fn component_stores(\n        stores: &Self::ExternalStores,\n");
    push_method_open(
        output,
        &format!("    ) -> &<{component_type} as HostProviderComponent>::Stores"),
    );
    output.push_str(&format!("        &stores.{field}\n    }}\n\n"));
    output.push_str("    fn component_state(\n        state: &mut Self::RunState,\n");
    push_method_open(
        output,
        &format!("    ) -> &mut <{component_type} as HostProviderComponent>::RunState"),
    );
    output.push_str(&format!("        &mut state.{field}\n    }}\n}}\n\n"));
}

fn push_method_open(output: &mut String, signature: &str) {
    output.push_str(signature);
    if signature.len() <= 100 {
        output.push_str(" {\n");
    } else {
        output.push_str("\n    {\n");
    }
}

fn push_stdlib_profile(output: &mut String, alias: &str, components: &HostedComponents) {
    output.push_str(&format!(
        "impl{} {alias}::gleam_stdlib::GleamStdlibHostProfile for {}",
        generics(components),
        profile_type(components),
    ));
    push_bounds_open(output, alias, components);
    output.push_str("    type Io = Io;\n}\n\n");
}

fn push_time_profile(output: &mut String, alias: &str, components: &HostedComponents) {
    output.push_str(&format!(
        "impl{} {alias}::gleam_time::GleamTimeHostProfile for {}",
        generics(components),
        profile_type(components),
    ));
    push_bounds_open(output, alias, components);
    output.push_str("    type Source = Source;\n}\n\n");
}

fn push_host_providers(output: &mut String, alias: &str, components: &HostedComponents) {
    let profile = profile_type(components);
    output.push_str(&format!(
        "pub fn host_providers{}() -> Result<ProviderSet{}, HostRegistrationError>",
        generics(components),
        generics(components),
    ));
    push_bounds_open(output, alias, components);
    let mutability = if components.has_multiple() {
        "mut "
    } else {
        ""
    };
    let first_type = component_type(alias, components.first());
    let registration =
        format!("<{first_type} as HostProviderComponentRegistration<{profile}>>::providers()?;");
    let first_registration = format!("    let {mutability}providers = {registration}\n");
    if first_registration.trim_end().len() <= 100 {
        output.push_str(&first_registration);
    } else if 8 + registration.len() <= 100 {
        output.push_str(&format!(
            "    let {mutability}providers =\n        {registration}\n"
        ));
    } else if components.capabilities() == HostedCapabilities::IoAndTime {
        output.push_str(&format!(
            "    let {mutability}providers =\n        <{first_type} as HostProviderComponentRegistration<\n            {profile},\n        >>::providers()?;\n"
        ));
    } else {
        output.push_str(&format!(
            "    let {mutability}providers = <{first_type} as HostProviderComponentRegistration<\n        {profile},\n    >>::providers()?;\n"
        ));
    }
    for component in components.remaining() {
        let component_type = component_type(alias, component);
        let registration = format!(
            "<{component_type} as HostProviderComponentRegistration<{profile}>>::providers()?"
        );
        if components.capabilities() == HostedCapabilities::IoAndTime {
            output.push_str(&format!(
                "    providers.extend(\n        <{component_type} as HostProviderComponentRegistration<\n            {profile},\n        >>::providers()?,\n    );\n"
            ));
        } else if components.capabilities() == HostedCapabilities::None {
            output.push_str(&format!(
                "    providers.extend(<{component_type} as HostProviderComponentRegistration<\n        {profile},\n    >>::providers()?);\n"
            ));
        } else {
            output.push_str(&format!(
                "    providers.extend(\n        {registration},\n    );\n"
            ));
        }
    }
    output.push_str(&format!(
        "    HostProviderSet::with_providers(Vec::<HostModule<{profile}>>::new(), providers)\n}}\n\n"
    ));
}

fn push_hosted_bind(
    output: &mut String,
    alias: &str,
    components: &HostedComponents,
    boundary: &PlainBindings,
) {
    let profile = profile_type(components);
    output.push_str(&format!(
        "pub fn bind{}(\n    builder: HostedModuleBuilder<{profile}>,\n) -> Result<(HostedModuleBindings<{profile}>, Functions), BindingError>",
        generics(components),
    ));
    push_bounds_open(output, alias, components);
    let mutability = if boundary.remaining.is_empty() {
        ""
    } else {
        "mut "
    };
    push_binding(
        output,
        &format!("({mutability}bindings, function_0)"),
        "builder",
        &boundary.first,
    );
    for (index, function) in boundary.remaining.iter().enumerate() {
        push_binding(
            output,
            &format!("function_{}", index + 1),
            "bindings",
            function,
        );
    }
    push_binding_result(output, boundary);
    output.push_str("}\n");
}

fn push_binding_result(output: &mut String, bindings: &PlainBindings) {
    let fields = bindings
        .functions()
        .enumerate()
        .map(|(index, function)| format!("{}: function_{index}", function.rust_name.as_str()))
        .collect::<Vec<_>>();
    let content = fields.join(", ");
    if content.len() <= 18 {
        output.push_str(&format!("    Ok((bindings, Functions {{ {content} }}))\n"));
    } else {
        output.push_str("    Ok((\n        bindings,\n        Functions {\n");
        for field in fields {
            output.push_str(&format!("            {field},\n"));
        }
        output.push_str("        },\n    ))\n");
    }
}

fn push_component_field(
    output: &mut String,
    alias: &str,
    component: &ComponentBinding,
    associated_type: &str,
) {
    let prefix = format!("    {}:", component_field(component));
    let type_path = format!(
        "<{} as HostProviderComponent>::{associated_type},",
        component_type(alias, component),
    );
    if prefix.len() + 1 + type_path.len() <= 100 {
        output.push_str(&format!("{prefix} {type_path}\n"));
    } else {
        output.push_str(&format!("{prefix}\n        {type_path}\n"));
    }
}

fn push_external_initialization(
    output: &mut String,
    alias: &str,
    component: &super::profile::ExternalComponent,
) {
    let field = component.state_field.as_str();
    let type_path = component_type(alias, &ComponentBinding::External(component.clone()));
    let initialization =
        format!("<{type_path} as HostProviderComponentInitialization>::initialize(");
    let opening = format!("            {field}: {initialization}\n");
    if opening.trim_end().len() <= 100 {
        output.push_str(&format!(
            "{opening}                &configurations.{configuration},\n            )?,\n",
            configuration = component.configuration_field.as_str(),
        ));
    } else {
        output.push_str(&format!(
            "            {field}:\n                {initialization}\n                    &configurations.{configuration},\n                )?,\n",
            configuration = component.configuration_field.as_str(),
        ));
    }
}

fn component_field(component: &ComponentBinding) -> &str {
    match component {
        ComponentBinding::Stdlib => "stdlib",
        ComponentBinding::Json => "json",
        ComponentBinding::Time => "time",
        ComponentBinding::External(component) => component.state_field.as_str(),
    }
}

fn component_type(alias: &str, component: &ComponentBinding) -> String {
    match component {
        ComponentBinding::Stdlib => format!("{alias}::gleam_stdlib::Component<Io>"),
        ComponentBinding::Json => format!("{alias}::gleam_json::Component"),
        ComponentBinding::Time => format!("{alias}::gleam_time::Component<Source>"),
        ComponentBinding::External(component) => {
            format!("{}::Component", component.crate_alias.as_str())
        }
    }
}

fn generics(components: &HostedComponents) -> &'static str {
    match components.capabilities() {
        HostedCapabilities::None => "",
        HostedCapabilities::Io => "<Io>",
        HostedCapabilities::IoAndTime => "<Io, Source>",
    }
}

fn profile_type(components: &HostedComponents) -> String {
    format!("Profile{}", generics(components))
}

fn push_bounds(output: &mut String, alias: &str, components: &HostedComponents) {
    output.push_str("where\n");
    output.push_str(&format!(
        "    Io: {alias}::gleam_stdlib::IoSink + 'static,\n"
    ));
    if components.has_time() {
        output.push_str(&format!("    Source: {alias}::gleam_time::TimeSource,\n"));
    }
}

fn push_bounds_open(output: &mut String, alias: &str, components: &HostedComponents) {
    if components.capabilities() == HostedCapabilities::None {
        output.push_str(" {\n");
    } else {
        output.push('\n');
        push_bounds(output, alias, components);
        output.push_str("{\n");
    }
}

fn push_function_field(output: &mut String, function: &FunctionBinding) {
    let arguments = argument_tuple(&function.arguments);
    let return_type = function.return_type.rust_type();
    let prefix = format!("    pub {}:", function.rust_name.as_str());
    let type_ = format!("Function<{arguments}, {return_type}>");
    let line = format!("{prefix} {type_},\n");
    if line.trim_end().len() <= 100 {
        output.push_str(&line);
    } else if 8 + type_.len() < 100 {
        output.push_str(&format!("{prefix}\n        {type_},\n"));
    } else {
        let (function_indent, content_indent, item_indent) =
            if prefix.len() + " Function<".len() <= 100 {
                output.push_str(&format!("{prefix} Function<\n        (\n"));
                ("    ", "        ", "            ")
            } else {
                output.push_str(&format!("{prefix}\n        Function<\n            (\n"));
                ("        ", "            ", "                ")
            };
        for argument in &function.arguments {
            output.push_str(&format!("{item_indent}{},\n", argument.rust_type()));
        }
        output.push_str(&format!(
            "{content_indent}),\n{content_indent}{return_type},\n{function_indent}>,\n"
        ));
    }
}

fn push_binding(output: &mut String, pattern: &str, owner: &str, function: &FunctionBinding) {
    let statement = format!(
        "    let {pattern} = {owner}.function(FunctionDeclaration::new({:?}))?;\n",
        function.gleam_name
    );
    if statement.trim_end().len() <= 100 {
        output.push_str(&statement);
    } else {
        output.push_str(&format!(
            "    let {pattern} =\n        {owner}.function(FunctionDeclaration::new({:?}))?;\n",
            function.gleam_name
        ));
    }
}

fn argument_tuple(arguments: &[Scalar]) -> String {
    match arguments {
        [] => "()".to_owned(),
        [argument] => format!("({},)", argument.rust_type()),
        arguments => format!(
            "({})",
            arguments
                .iter()
                .map(Scalar::rust_type)
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

impl Scalar {
    fn import(&self) -> Option<&'static str> {
        match self {
            Self::Int => Some("BigInt"),
            Self::String => Some("EcoString"),
            Self::BitArray => Some("BitArrayValue"),
            Self::Float | Self::UtfCodepoint | Self::Bool | Self::Nil => None,
        }
    }

    fn rust_type(&self) -> &'static str {
        match self {
            Self::Int => "BigInt",
            Self::Float => "f64",
            Self::String => "EcoString",
            Self::BitArray => "BitArrayValue",
            Self::UtfCodepoint => "char",
            Self::Bool => "bool",
            Self::Nil => "()",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{hosted, plain, push_function_field};
    use crate::builtin::BuiltInProvider;
    use crate::embedding::boundary::{FunctionBinding, PlainBindings, Scalar};
    use crate::embedding::identifier::RustIdentifier;
    use crate::embedding::profile::{ExternalComponent, HostedBindings, HostedComponents};
    use std::fs;

    #[test]
    fn renders_deterministic_plain_bindings_for_all_scalar_paths() {
        let bindings = PlainBindings {
            geam_alias: RustIdentifier::parse("runtime")
                .expect("fixture crate alias should be valid"),
            root_module: "inventory_rules".to_owned(),
            first: FunctionBinding {
                gleam_name: "async".to_owned(),
                rust_name: RustIdentifier::parse("async")
                    .expect("keyword should use a raw identifier"),
                arguments: Vec::new(),
                return_type: Scalar::Nil,
            },
            remaining: vec![FunctionBinding {
                gleam_name: "all_values".to_owned(),
                rust_name: RustIdentifier::parse("all_values")
                    .expect("fixture function should be valid"),
                arguments: vec![
                    Scalar::Int,
                    Scalar::Float,
                    Scalar::String,
                    Scalar::BitArray,
                    Scalar::UtfCodepoint,
                    Scalar::Bool,
                    Scalar::Nil,
                ],
                return_type: Scalar::String,
            }],
        };

        let source = plain(&bindings);
        assert_eq!(
            source,
            r#"// Generated by `geam embedding sync`. Do not edit.

use runtime::embedding::BigInt;
use runtime::embedding::BindingError;
use runtime::embedding::BitArrayValue;
use runtime::embedding::EcoString;
use runtime::embedding::Function;
use runtime::embedding::FunctionDeclaration;
use runtime::embedding::ModuleBindings;
use runtime::embedding::ModuleBuilder;

pub const ROOT_MODULE: &str = "inventory_rules";

pub struct Functions {
    pub r#async: Function<(), ()>,
    pub all_values: Function<(BigInt, f64, EcoString, BitArrayValue, char, bool, ()), EcoString>,
}

pub fn bind(builder: ModuleBuilder) -> Result<(ModuleBindings, Functions), BindingError> {
    let (mut bindings, function_0) = builder.function(FunctionDeclaration::new("async"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("all_values"))?;
    Ok((bindings, Functions { r#async: function_0, all_values: function_1 }))
}
"#,
        );
        assert_eq!(plain(&bindings), source);
    }

    #[test]
    fn keeps_long_representable_identifiers_rustfmt_stable() {
        let name = "function_with_a_deliberately_long_but_representable_name_that_remains_part_of_the_public_boundary";
        let bindings = PlainBindings {
            geam_alias: RustIdentifier::parse("runtime")
                .expect("fixture crate alias should be valid"),
            root_module: "boundary".to_owned(),
            first: FunctionBinding {
                gleam_name: name.to_owned(),
                rust_name: RustIdentifier::parse(name)
                    .expect("long identifier should remain representable"),
                arguments: vec![
                    Scalar::Int,
                    Scalar::Float,
                    Scalar::String,
                    Scalar::BitArray,
                    Scalar::UtfCodepoint,
                    Scalar::Bool,
                    Scalar::Nil,
                ],
                return_type: Scalar::String,
            },
            remaining: Vec::new(),
        };
        assert_rustfmt_stable("long plain", &plain(&bindings));
    }

    #[test]
    fn renders_the_longest_scalar_function_field_exactly() {
        let short = FunctionBinding {
            gleam_name: "all_bits".to_owned(),
            rust_name: RustIdentifier::parse("all_bits").expect("fixture function should be valid"),
            arguments: vec![Scalar::BitArray; 7],
            return_type: Scalar::BitArray,
        };
        let long_name = "function_with_a_deliberately_long_but_representable_name_that_remains_part_of_the_public_boundary";
        let long = FunctionBinding {
            gleam_name: long_name.to_owned(),
            rust_name: RustIdentifier::parse(long_name)
                .expect("long fixture function should be valid"),
            arguments: vec![Scalar::BitArray; 7],
            return_type: Scalar::BitArray,
        };
        let mut field = String::new();

        push_function_field(&mut field, &short);
        push_function_field(&mut field, &long);

        assert_eq!(
            field,
            r#"    pub all_bits: Function<
        (
            BitArrayValue,
            BitArrayValue,
            BitArrayValue,
            BitArrayValue,
            BitArrayValue,
            BitArrayValue,
            BitArrayValue,
        ),
        BitArrayValue,
    >,
    pub function_with_a_deliberately_long_but_representable_name_that_remains_part_of_the_public_boundary:
        Function<
            (
                BitArrayValue,
                BitArrayValue,
                BitArrayValue,
                BitArrayValue,
                BitArrayValue,
                BitArrayValue,
                BitArrayValue,
            ),
            BitArrayValue,
        >,
"#,
        );
        assert_rustfmt_stable(
            "long scalar field",
            &format!("pub struct Functions {{\n{field}}}\n"),
        );
    }

    #[test]
    fn renders_exact_host_capability_and_component_closures() {
        let stdlib = hosted_source(HostedComponents::from_builtin(BuiltInProvider::Stdlib));
        assert!(stdlib.contains("pub struct Profile<Io>"));
        assert!(stdlib.contains("pub struct ProviderConfigurations;"));
        assert!(stdlib.contains("gleam_stdlib::Component<Io>"));
        assert!(!stdlib.contains("gleam_json::Component"));
        assert!(!stdlib.contains("gleam_time::Component"));
        assert!(!stdlib.contains("HostProviderComponentInitialization"));

        let json = hosted_source(HostedComponents::from_builtin(BuiltInProvider::Json));
        assert!(json.contains("pub struct Profile<Io>"));
        assert!(json.contains("gleam_stdlib::Component<Io>"));
        assert!(json.contains("gleam_json::Component"));
        assert!(!json.contains("gleam_time::Component"));

        let time = hosted_source(HostedComponents::from_builtin(BuiltInProvider::Time));
        assert!(time.contains("pub struct Profile<Io, Source>"));
        assert!(
            time.contains(
                "pub type ProviderSet<Io, Source> = HostProviderSet<Profile<Io, Source>>;"
            )
        );
        assert!(time.contains("gleam_stdlib::Component<Io>"));
        assert!(time.contains("gleam_time::Component<Source>"));
        assert!(time.contains("Source: runtime::gleam_time::TimeSource"));
        assert!(!time.contains("gleam_json::Component"));

        let mut json_and_time = HostedComponents::from_builtin(BuiltInProvider::Json);
        json_and_time.extend(HostedComponents::from_builtin(BuiltInProvider::Time));
        let json_and_time = hosted_source(json_and_time);
        assert!(json_and_time.contains("gleam_json::Component"));
        assert!(json_and_time.contains("gleam_time::Component<Source>"));

        for (label, source) in [
            ("stdlib", stdlib),
            ("json", json),
            ("time", time),
            ("json and time", json_and_time),
        ] {
            assert_rustfmt_stable(label, &source);
        }
    }

    #[test]
    fn renders_external_alias_configuration_and_mixed_state_without_accessors() {
        let external = external_components();
        let external_only = hosted_source(external_components());
        assert!(external_only.contains("pub struct Profile;"));
        assert!(external_only.contains("pub example_text_pattern: HostProviderConfiguration"));
        assert!(external_only.contains("patterns::Component"));
        assert!(external_only.contains("HostProviderInitializationError"));
        assert!(!external_only.contains("pub fn stdlib("));
        assert!(!external_only.contains("gleam_stdlib::Component"));

        let mut two_external = external_components();
        two_external.extend(HostedComponents::from_external(ExternalComponent {
            package: "other_provider".to_owned(),
            configuration_field: identifier("other_provider"),
            state_field: identifier("provider_other_provider"),
            crate_alias: identifier("other"),
        }));
        let two_external = hosted_source(two_external);
        assert!(two_external.contains("pub other_provider: HostProviderConfiguration"));
        assert!(two_external.contains("other::Component"));

        let mut two_short = HostedComponents::from_external(ExternalComponent {
            package: "a".to_owned(),
            configuration_field: identifier("a"),
            state_field: identifier("provider_a"),
            crate_alias: identifier("p"),
        });
        two_short.extend(HostedComponents::from_external(ExternalComponent {
            package: "b".to_owned(),
            configuration_field: identifier("b"),
            state_field: identifier("provider_b"),
            crate_alias: identifier("q"),
        }));
        let two_short = hosted_source(two_short);

        let long_external = hosted_source(HostedComponents::from_external(ExternalComponent {
            package: "package_with_a_deliberately_long_name".to_owned(),
            configuration_field: identifier("package_with_a_deliberately_long_name"),
            state_field: identifier("provider_package_with_a_deliberately_long_name"),
            crate_alias: identifier("provider_with_a_deliberately_long_cargo_alias"),
        }));

        let mut mixed = HostedComponents::from_builtin(BuiltInProvider::Stdlib);
        mixed.extend(external);
        let mixed = hosted_source(mixed);
        assert!(mixed.contains("pub struct Profile<Io>"));
        assert!(mixed.contains("pub type ProviderSet<Io> = HostProviderSet<Profile<Io>>;"));
        assert!(mixed.contains("gleam_stdlib::Component<Io>"));
        assert!(mixed.contains("patterns::Component"));
        assert!(mixed.contains("pub fn stdlib("));
        assert!(!mixed.contains("pub fn provider_example_text_pattern"));

        assert_rustfmt_stable("external", &external_only);
        assert_rustfmt_stable("two external", &two_external);
        assert_rustfmt_stable("two short external", &two_short);
        assert_rustfmt_stable("long external", &long_external);
        assert_rustfmt_stable("mixed", &mixed);
    }

    fn hosted_source(components: HostedComponents) -> String {
        hosted(&HostedBindings {
            boundary: PlainBindings {
                geam_alias: identifier("runtime"),
                root_module: "inventory_rules".to_owned(),
                first: FunctionBinding {
                    gleam_name: "normalize".to_owned(),
                    rust_name: identifier("normalize"),
                    arguments: vec![Scalar::String],
                    return_type: Scalar::String,
                },
                remaining: vec![FunctionBinding {
                    gleam_name: "ready".to_owned(),
                    rust_name: identifier("ready"),
                    arguments: Vec::new(),
                    return_type: Scalar::Bool,
                }],
            },
            components,
        })
    }

    fn external_components() -> HostedComponents {
        HostedComponents::from_external(ExternalComponent {
            package: "example_text_pattern".to_owned(),
            configuration_field: identifier("example_text_pattern"),
            state_field: identifier("provider_example_text_pattern"),
            crate_alias: identifier("patterns"),
        })
    }

    fn identifier(value: &str) -> RustIdentifier {
        RustIdentifier::parse(value).expect("fixture identifier should be valid")
    }

    fn assert_rustfmt_stable(label: &str, source: &str) {
        let directory = tempfile::tempdir().expect("temporary directory should be created");
        let path = directory.path().join("geam_bindings.rs");
        fs::write(&path, source).expect("generated source should be written");
        for style_edition in ["2015", "2024"] {
            let output = std::process::Command::new("rustfmt")
                .args([
                    "--edition",
                    "2024",
                    "--style-edition",
                    style_edition,
                    "--check",
                ])
                .arg(&path)
                .output()
                .expect("rustfmt should start");
            let stdout = String::from_utf8_lossy(&output.stdout);
            let stderr = String::from_utf8_lossy(&output.stderr);
            assert!(
                output.status.success(),
                "{label} generated source should already be formatted under style edition {style_edition}:\nstdout:\n{stdout}\nstderr:\n{stderr}\nsource:\n{source}",
            );
        }
    }
}
