[package]
name = "native-function-views-embedding"
version = "0.1.0"
edition = "2024"
publish = false

[package.metadata.geam.embedding]
generate = "both"

[dependencies]
geam = { version = "=0.2.3", default-features = false, features = ["embedding", "tokio", "geam-builtin", "gleam-stdlib"] }
geam-native-function-views-fixture = { path = "../provider" }
tokio = { version = "1", features = ["rt"] }

[patch.crates-io]
geam = { path = "../../../.." }

[workspace]
resolver = "3"
