// Generated by `geam embedding sync`. Do not edit.

use geam::HostComponentProfile;
use geam::HostModule;
use geam::HostProfile;
use geam::HostProviderComponent;
use geam::HostProviderComponentInitialization;
use geam::HostProviderComponentRegistration;
use geam::HostProviderConfiguration;
use geam::HostProviderInitializationError;
use geam::HostProviderSet;
use geam::HostRegistrationError;

use geam::embedding::BindingError;
use geam::embedding::EcoString;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::HostedModuleBindings;
use geam::embedding::HostedModuleBuilder;
use geam::embedding::HostedProject;
use geam::embedding::InputShape;

pub const ROOT_MODULE: &str = "geam_rust_embedding_provider";

pub struct Profile;

pub type ProviderSet = HostProviderSet<Profile>;

#[derive(Default)]
pub struct Stores {
    provider_example_text_pattern: <patterns::Component as HostProviderComponent>::Stores,
}

pub struct RunStateInputs {
    pub example_text_pattern: HostProviderConfiguration,
}

impl RunStateInputs {
    pub fn initialize(self) -> Result<RunState, HostProviderInitializationError> {
        Ok(RunState {
            provider_example_text_pattern:
                <patterns::Component as HostProviderComponentInitialization>::initialize(
                    &self.example_text_pattern,
                )?,
        })
    }
}

pub struct RunState {
    provider_example_text_pattern: <patterns::Component as HostProviderComponent>::RunState,
}

impl HostProfile for Profile {
    type ExternalStores = Stores;
    type RunState = RunState;
}

impl HostComponentProfile<patterns::Component> for Profile {
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<patterns::Component as HostProviderComponent>::Stores {
        &stores.provider_example_text_pattern
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <patterns::Component as HostProviderComponent>::RunState {
        &mut state.provider_example_text_pattern
    }
}

pub fn host_providers() -> Result<ProviderSet, HostRegistrationError> {
    let providers =
        <patterns::Component as HostProviderComponentRegistration<Profile>>::providers()?;
    HostProviderSet::with_providers(Vec::<HostModule<Profile>>::new(), providers)
}

pub fn project() -> HostedProject<Profile> {
    HostedProject::new(
        concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"),
        ROOT_MODULE,
        host_providers,
    )
}

#[allow(clippy::type_complexity)]
pub struct Functions {
    pub matches: Function<(EcoString, EcoString), Result<bool, EcoString>, Function0Input>,
}

pub struct Function0Input;

impl InputShape<(EcoString, EcoString)> for Function0Input {}

pub fn bind(
    builder: HostedModuleBuilder<Profile>,
) -> Result<(HostedModuleBindings<Profile>, Functions), BindingError> {
    let (bindings, function_0) = builder.function(FunctionDeclaration::new("matches"))?;
    Ok((
        bindings,
        Functions {
            matches: function_0.with_input_shape(),
        },
    ))
}
