// Generated by `geam embedding sync`. Do not edit.

use geam::HostComponentProfile;
use geam::HostModule;
use geam::HostProfile;
use geam::HostProviderComponent;
use geam::HostProviderComponentRegistration;
use geam::HostProviderSet;
use geam::HostRegistrationError;

use geam::embedding::BindingError;
use geam::embedding::EcoString;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::HostedModuleBindings;
use geam::embedding::HostedModuleBuilder;
use geam::embedding::HostedProject;
use geam::embedding::InputShape;
use std::marker::PhantomData;

pub const ROOT_MODULE: &str = "geam_rust_embedding_io";

pub struct Profile<Io>(PhantomData<fn() -> Io>);

pub type ProviderSet<Io> = HostProviderSet<Profile<Io>>;

pub struct Stores<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores,
}

impl<Io> Default for Stores<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn default() -> Self {
        Self {
            stdlib: Default::default(),
        }
    }
}

pub struct RunStateInputs<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub stdlib: geam::gleam_stdlib::GleamStdlibRunState<Io>,
}

impl<Io> RunStateInputs<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub fn initialize(self) -> RunState<Io> {
        RunState {
            stdlib: self.stdlib,
        }
    }
}

pub struct RunState<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState,
}

impl<Io> RunState<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub fn stdlib(&self) -> &geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &self.stdlib
    }

    pub fn stdlib_mut(&mut self) -> &mut geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &mut self.stdlib
    }
}

impl<Io> HostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type ExternalStores = Stores<Io>;
    type RunState = RunState<Io>;
}

impl<Io> HostComponentProfile<geam::gleam_stdlib::Component<Io>> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores {
        &stores.stdlib
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState {
        &mut state.stdlib
    }
}

impl<Io> geam::gleam_stdlib::GleamStdlibHostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type Io = Io;
}

pub fn host_providers<Io>() -> Result<ProviderSet<Io>, HostRegistrationError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let providers = <geam::gleam_stdlib::Component<Io> as HostProviderComponentRegistration<
        Profile<Io>,
    >>::providers()?;
    HostProviderSet::with_providers(Vec::<HostModule<Profile<Io>>>::new(), providers)
}

pub fn project<Io>() -> HostedProject<Profile<Io>>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    HostedProject::new(
        concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"),
        ROOT_MODULE,
        host_providers::<Io>,
    )
}

#[allow(clippy::type_complexity)]
pub struct Functions {
    pub announce: Function<(EcoString,), EcoString, Function0Input>,
}

pub struct Function0Input;

impl InputShape<(EcoString,)> for Function0Input {}

pub fn bind<Io>(
    builder: HostedModuleBuilder<Profile<Io>>,
) -> Result<(HostedModuleBindings<Profile<Io>>, Functions), BindingError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let (bindings, function_0) = builder.function(FunctionDeclaration::new("announce"))?;
    Ok((
        bindings,
        Functions {
            announce: function_0.with_input_shape(),
        },
    ))
}
