// Generated by `geam embedding sync`. Do not edit.

use geam::HostComponentProfile;
use geam::HostProfile;
use geam::HostProviderComponent;
use geam::HostProviderComponentInitialization;
use geam::HostProviderComponentRegistration as ComponentRegistration;
use geam::HostProviderConfiguration;
use geam::HostProviderInitializationError;
use geam::HostProviderSet;
use geam::HostRegistrationError;
use geam::HostWorkProfile;

use geam::embedding::BigInt;
use geam::embedding::BindingError;
use geam::embedding::BitArrayValue;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::HostedModule;
use geam::embedding::HostedModuleBindings;
use geam::embedding::HostedModuleBuilder;
use geam::embedding::HostedProject;
use geam::embedding::InputShape;
use geam::embedding::PreparedError;
use geam::embedding::StringValue;
use std::marker::PhantomData;

pub const ROOT_MODULE: &str = "raw_string_values_embedding";

mod program;

pub struct Profile<Io>(PhantomData<fn() -> Io>);

pub type ProviderSet<Io> = HostProviderSet<Profile<Io>>;

pub struct Stores<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    future: <geam::FutureComponent as HostProviderComponent>::Stores,
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores,
    provider_raw_string_values_fixture:
        <geam_raw_string_values_fixture::Component as HostProviderComponent>::Stores,
}

impl<Io> Default for Stores<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn default() -> Self {
        Self {
            future: Default::default(),
            stdlib: Default::default(),
            provider_raw_string_values_fixture: Default::default(),
        }
    }
}

pub struct RunStateInputs<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub stdlib: geam::gleam_stdlib::GleamStdlibRunState<Io>,
    pub raw_string_values_fixture: HostProviderConfiguration,
}

impl<Io> RunStateInputs<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub fn initialize(self) -> Result<RunState<Io>, HostProviderInitializationError> {
        Ok(RunState {
            future: (),
            stdlib: self.stdlib,
            provider_raw_string_values_fixture:
                <geam_raw_string_values_fixture::Component as HostProviderComponentInitialization>::initialize(
                    &self.raw_string_values_fixture,
                )?,
        })
    }
}

pub struct RunState<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    future: <geam::FutureComponent as HostProviderComponent>::RunState,
    stdlib: <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState,
    provider_raw_string_values_fixture:
        <geam_raw_string_values_fixture::Component as HostProviderComponent>::RunState,
}

impl<Io> RunState<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    pub fn stdlib(&self) -> &geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &self.stdlib
    }

    pub fn stdlib_mut(&mut self) -> &mut geam::gleam_stdlib::GleamStdlibRunState<Io> {
        &mut self.stdlib
    }
}

impl<Io> HostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type ExternalStores = Stores<Io>;
    type RunState = RunState<Io>;
    type ExecutionState = ();
}

impl<Io> HostWorkProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type Work = geam::FutureComponent;
}

impl<Io> HostComponentProfile<geam::FutureComponent> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::FutureComponent as HostProviderComponent>::Stores {
        &stores.future
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::FutureComponent as HostProviderComponent>::RunState {
        &mut state.future
    }
}

impl<Io> HostComponentProfile<geam::gleam_stdlib::Component<Io>> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam::gleam_stdlib::Component<Io> as HostProviderComponent>::Stores {
        &stores.stdlib
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam::gleam_stdlib::Component<Io> as HostProviderComponent>::RunState {
        &mut state.stdlib
    }
}

impl<Io> HostComponentProfile<geam_raw_string_values_fixture::Component> for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    fn component_stores(
        stores: &Self::ExternalStores,
    ) -> &<geam_raw_string_values_fixture::Component as HostProviderComponent>::Stores {
        &stores.provider_raw_string_values_fixture
    }

    fn component_state(
        state: &mut Self::RunState,
    ) -> &mut <geam_raw_string_values_fixture::Component as HostProviderComponent>::RunState {
        &mut state.provider_raw_string_values_fixture
    }
}

impl<Io> geam::gleam_stdlib::GleamStdlibHostProfile for Profile<Io>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    type Io = Io;
}

pub fn host_providers<Io>() -> Result<ProviderSet<Io>, HostRegistrationError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let mut providers =
        <geam::gleam_stdlib::Component<Io> as ComponentRegistration<Profile<Io>>>::providers()?;
    let additional_providers =
        <geam_raw_string_values_fixture::Component as ComponentRegistration<
            Profile<Io>,
        >>::providers()?;
    providers.extend(additional_providers);
    HostProviderSet::from_providers(providers)
}

#[allow(dead_code)]
pub fn project<Io>() -> HostedProject<Profile<Io>>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    HostedProject::new(
        concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"),
        ROOT_MODULE,
        host_providers::<Io>,
    )
}

#[allow(clippy::type_complexity)]
pub struct Functions {
    pub main: Function<(), (), Function0Input>,
    pub strip_prefix: Function<(StringValue,), StringValue, Function1Input>,
    pub count_prefix: Function<(StringValue, BigInt), BigInt, Function2Input>,
    pub utf16_encode: Function<(StringValue,), BitArrayValue, Function3Input>,
    pub utf32_encode: Function<(StringValue,), BitArrayValue, Function4Input>,
}

pub struct Function0Input;

impl InputShape<()> for Function0Input {}

pub struct Function1Input;

impl InputShape<(StringValue,)> for Function1Input {}

pub struct Function2Input;

impl InputShape<(StringValue, BigInt)> for Function2Input {}

pub struct Function3Input;

impl InputShape<(StringValue,)> for Function3Input {}

pub struct Function4Input;

impl InputShape<(StringValue,)> for Function4Input {}

#[allow(dead_code)]
pub fn bind<Io>(
    builder: HostedModuleBuilder<Profile<Io>>,
) -> Result<(HostedModuleBindings<Profile<Io>>, Functions), BindingError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let (mut bindings, function_0) = builder.function(FunctionDeclaration::new("main"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("strip_prefix"))?;
    let function_2 = bindings.function(FunctionDeclaration::new("count_prefix"))?;
    let function_3 = bindings.function(FunctionDeclaration::new("utf16_encode"))?;
    let function_4 = bindings.function(FunctionDeclaration::new("utf32_encode"))?;
    Ok((
        bindings,
        Functions {
            main: function_0.with_input_shape(),
            strip_prefix: function_1.with_input_shape(),
            count_prefix: function_2.with_input_shape(),
            utf16_encode: function_3.with_input_shape(),
            utf32_encode: function_4.with_input_shape(),
        },
    ))
}

#[allow(dead_code)]
pub fn load<Io>() -> Result<(HostedModule<Profile<Io>>, Functions), PreparedError>
where
    Io: geam::gleam_stdlib::IoSink + 'static,
{
    let mut bindings = program::PROGRAM.load(host_providers::<Io>()?)?;
    let function_0 = bindings.function(FunctionDeclaration::new("main"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("strip_prefix"))?;
    let function_2 = bindings.function(FunctionDeclaration::new("count_prefix"))?;
    let function_3 = bindings.function(FunctionDeclaration::new("utf16_encode"))?;
    let function_4 = bindings.function(FunctionDeclaration::new("utf32_encode"))?;
    Ok((
        bindings.seal(),
        Functions {
            main: function_0.with_input_shape(),
            strip_prefix: function_1.with_input_shape(),
            count_prefix: function_2.with_input_shape(),
            utf16_encode: function_3.with_input_shape(),
            utf32_encode: function_4.with_input_shape(),
        },
    ))
}
