// Generated by `geam embedding sync`. Do not edit.

use geam::embedding::BigInt;
use geam::embedding::BindingError;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::InputShape;
use geam::embedding::List;
use geam::embedding::ModuleBindings;
use geam::embedding::ModuleBuilder;
use geam::embedding::Project;
use geam::embedding::StringValue;

pub const ROOT_MODULE: &str = "geam_rust_embedding_data";

pub fn project() -> Project {
    Project::new(concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"), ROOT_MODULE)
}

#[allow(dead_code, clippy::type_complexity)]
pub struct Functions {
    pub review: Function<
        (List<(StringValue, BigInt)>,),
        List<Result<(StringValue, BigInt), StringValue>>,
        Function0Input,
    >,
    pub total:
        Function<(List<Result<(StringValue, BigInt), StringValue>>,), BigInt, Function1Input>,
}

pub struct Function0Input;

impl<Input0> InputShape<(Input0,)> for Function0Input {}

pub struct Function1Input;

impl<Input0> InputShape<(Input0,)> for Function1Input {}

#[allow(dead_code)]
pub fn bind(builder: ModuleBuilder) -> Result<(ModuleBindings, Functions), BindingError> {
    let (mut bindings, function_0) = builder.function(FunctionDeclaration::new("review"))?;
    let function_1 = bindings.function(FunctionDeclaration::new("total"))?;
    Ok((
        bindings,
        Functions {
            review: function_0.with_input_shape(),
            total: function_1.with_input_shape(),
        },
    ))
}
