use camino::{Utf8Path, Utf8PathBuf};
use std::path::Path;
use toml_edit::{ArrayOfTables, DocumentMut, Item, Table, value};

pub(super) enum RunnerControl<'a> {
    Check,
    Run(&'a [(String, Utf8PathBuf)]),
    Prepare(&'a Path),
}

pub(super) const CONTROL_ENV: &str = "GEAM_RUNNER_CONTROL";

impl RunnerControl<'_> {
    pub(super) fn encode(self, root: &Utf8Path, module: &str) -> String {
        let mut document = DocumentMut::new();
        document["schema"] = value(1);
        document["mode"] = value(match self {
            Self::Check => "check",
            Self::Run(_) => "run",
            Self::Prepare(_) => "prepare",
        });
        document["project_root"] = value(root.as_str());
        document["module"] = value(module);
        match self {
            Self::Check => {}
            Self::Run(configurations) => {
                let mut tables = ArrayOfTables::new();
                for (package, path) in configurations {
                    let mut table = Table::new();
                    table["package"] = value(package);
                    table["path"] = value(path.as_str());
                    tables.push(table);
                }
                document["configurations"] = Item::ArrayOfTables(tables);
            }
            Self::Prepare(output) => {
                // Build owns this temporary path: a UTF-8 project directory and
                // an ASCII filename generated by tempfile.
                document["output"] = value(output.to_string_lossy().as_ref());
            }
        }
        document.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::RunnerControl;
    use camino::{Utf8Path, Utf8PathBuf};
    use std::path::Path;

    #[test]
    fn encodes_each_control_mode_without_application_arguments() {
        let root = Utf8Path::new("project space");
        assert_eq!(
            RunnerControl::Check.encode(root, "worker"),
            "schema = 1\nmode = \"check\"\nproject_root = \"project space\"\nmodule = \"worker\"\n"
        );
        assert_eq!(
            RunnerControl::Run(&[]).encode(root, "worker"),
            "schema = 1\nmode = \"run\"\nproject_root = \"project space\"\nmodule = \"worker\"\n"
        );
        assert_eq!(
            RunnerControl::Run(&[
                ("images".into(), Utf8PathBuf::from("settings/a=b.toml")),
                ("search".into(), Utf8PathBuf::from("settings/검색.toml")),
            ])
            .encode(root, "worker"),
            concat!(
                "schema = 1\nmode = \"run\"\nproject_root = \"project space\"\nmodule = \"worker\"\n",
                "\n[[configurations]]\npackage = \"images\"\npath = \"settings/a=b.toml\"\n",
                "\n[[configurations]]\npackage = \"search\"\npath = \"settings/검색.toml\"\n",
            )
        );
        assert_eq!(
            RunnerControl::Prepare(Path::new("build/geam/program.rs")).encode(root, "worker"),
            concat!(
                "schema = 1\nmode = \"prepare\"\nproject_root = \"project space\"\nmodule = \"worker\"\n",
                "output = \"build/geam/program.rs\"\n",
            )
        );
    }

    #[test]
    fn serializes_control_strings_with_toml_escaping() {
        assert_eq!(
            RunnerControl::Run(&[(
                "images".into(),
                Utf8PathBuf::from("C:\\space dir\\quote\"=한글\n.toml"),
            )])
            .encode(Utf8Path::new("root\t\"path"), "tools/report"),
            concat!(
                "schema = 1\nmode = \"run\"\nproject_root = 'root\t\"path'\nmodule = \"tools/report\"\n",
                "\n[[configurations]]\npackage = \"images\"\npath = '''\nC:\\space dir\\quote\"=한글\n.toml'''\n",
            )
        );
    }
}
