// Generated by `geam embedding sync`. Do not edit.

use geam::embedding::BigInt;
use geam::embedding::BindingError;
use geam::embedding::Function;
use geam::embedding::FunctionDeclaration;
use geam::embedding::InputShape;
use geam::embedding::ModuleBindings;
use geam::embedding::ModuleBuilder;
use geam::embedding::Project;

pub const ROOT_MODULE: &str = "geam_rust_embedding_first_call";

pub fn project() -> Project {
    Project::new(concat!(env!("CARGO_MANIFEST_DIR"), "/gleam"), ROOT_MODULE)
}

#[allow(clippy::type_complexity)]
pub struct Functions {
    pub double: Function<(BigInt,), BigInt, Function0Input>,
}

pub struct Function0Input;

impl InputShape<(BigInt,)> for Function0Input {}

pub fn bind(builder: ModuleBuilder) -> Result<(ModuleBindings, Functions), BindingError> {
    let (bindings, function_0) = builder.function(FunctionDeclaration::new("double"))?;
    Ok((
        bindings,
        Functions {
            double: function_0.with_input_shape(),
        },
    ))
}
